#ifndef SLANG_UNIX_CPP_COMPILER_UTIL_H
#define SLANG_UNIX_CPP_COMPILER_UTIL_H

#include "../slang-list.h"
#include "../slang-string.h"

#include "../slang-process-util.h"

#include "../slang-cpp-compiler.h"

namespace Slang {

struct UnixCPPCompilerUtil
{
        /// Run compiler with command line (typically generated by calcArgs). Output placed in outResult.
    static SlangResult executeCompiler(const CommandLine& commandLine, ExecuteResult& outResult);

        /// Calculate the command line args
    static void calcArgs(const CPPCompiler::CompileOptions& options, CommandLine& cmdLine);
};

} // namespace Slang

#endif 
