#!/usr/bin/env python3
"""
generate-slang-bindings.py
Reads include/slang.h and emits the C++ enum-metadata translation unit:
  source/slang-wasm-wasi/slang-wasm-wasi-enum-generated.cpp
     A C++ translation unit containing a static JSON blob of all Slang enum values,
     exported from the WASM module via slang_wasm_enum_metadata_ptr/len. Dynamic
     runtimes (Go, Python, Rust) call these two exports at startup to resolve enum
     integer values without hardcoding them.

Optionally, when --java-out is supplied, it also emits one Java source file per
Slang enum under that directory:
  <java-out>/*.java
     One Java source file per Slang enum, with integer values baked in from slang.h.
     These provide compile-time type safety and IDE autocomplete for the Java binding.
     The Java enums are NOT generated by default — pass --java-out to opt in.

The C++ output is not committed to the repository (it is gitignored). CMake runs
the generator at configure time whenever the C++ output is missing or slang.h is
newer than it (see source/slang-wasm-wasi/CMakeLists.txt).

Usage:
  python source/slang-wasm-wasi/tools/generate-slang-bindings.py [--slang-h PATH] [--cpp-out PATH] [--java-out DIR] [--java-package PKG]

Defaults assume the script is run from the repository root. --java-out has no
default; omit it to skip Java generation entirely. --java-package controls the
package declared in the generated Java sources (default
org.shaderslang.wasm.enums).
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from typing import Optional

# ---------------------------------------------------------------------------
# Enum specification table
# ---------------------------------------------------------------------------


@dataclass
class EnumSpec:
    c_name: str         # C++ enum name, e.g. "SlangCompileTarget" or "CompilerOptionName"
    java_name: str      # Java enum class name, e.g. "Target"
    javadoc: str        # One-sentence Javadoc summary
    # Prefix to strip from member names when forming Java constant names:
    #   None  → auto-detect the longest common prefix ending with '_'
    #   ""    → keep member names as-is (CompilerOptionName: already PascalCase)
    #   "FOO_" → strip exactly "FOO_" from each member name
    prefix: Optional[str] = None


ENUM_CONFIG = [
    EnumSpec("SlangCompileTarget",     "Target",            "Compile output format."),
    EnumSpec("SlangStage",             "Stage",             "Pipeline stage."),
    EnumSpec("CompilerOptionName",     "CompilerOptionName","Compiler option key.",           prefix=""),
    EnumSpec("SlangTypeKind",          "TypeKind",          "Reflection type kind."),
    EnumSpec("SlangScalarType",        "ScalarType",        "Scalar element type."),
    EnumSpec("SlangResourceAccess",    "ResourceAccess",    "Resource access mode."),
    EnumSpec("SlangResourceShape",     "ResourceShape",     "Resource shape."),
    EnumSpec("SlangParameterCategory", "ParameterCategory", "Parameter binding category."),
    EnumSpec("SlangLayoutRules",       "LayoutRules",       "Layout rule set."),
    EnumSpec("SlangMatrixLayoutMode",  "MatrixLayoutMode",  "Matrix storage order."),
    EnumSpec("SlangFloatingPointMode", "FloatingPointMode", "Floating-point mode."),
    EnumSpec("SlangOptimizationLevel", "OptimizationLevel", "Optimisation level."),
    EnumSpec("SlangDebugInfoLevel",    "DebugInfoLevel",    "Debug info verbosity."),
    EnumSpec("SlangPassThrough",       "PassThrough",       "Downstream compiler."),
    # SlangTargetFlags is an anonymous enum; identify members by prefix.
    EnumSpec("SlangTargetFlags",       "TargetFlags",       "Target flag bits.",             prefix="SLANG_TARGET_FLAG_"),
]

# Member names matching these patterns are sentinels that should be excluded.
_SENTINEL_RE = re.compile(
    r"(?:"
    r"_COUNT_OF$|_COUNT$|COUNT_OF$|CountOf$|CountOfParsableOptions$"
    r"|_FORCE_UINT32$|_FORCE_INT32$|_COUNT_V1$"
    r")"
)

# Member names containing these substrings are deprecated/removed and excluded.
_DEPRECATED_RE = re.compile(r"_DEPRECATED|^REMOVED_")

# ---------------------------------------------------------------------------
# Value parsing
# ---------------------------------------------------------------------------


def _eval_value(expr: str, member_map: dict) -> Optional[int]:
    """Evaluate a simple enum value expression.

    Returns the integer value, or None when the expression references another
    member (alias) or is too complex to evaluate statically (bitwise OR, etc.).
    Callers treat None as a signal to skip the member.
    """
    expr = expr.strip()
    # Hex literal, tolerating a C++ integer-literal suffix (u/U/l/L in any
    # combination, e.g. 0x10UL) so a suffixed value isn't silently dropped.
    m = re.match(r"^(-?0x[0-9A-Fa-f]+)[uUlL]*$", expr)
    if m:
        return int(m.group(1), 16)
    # Decimal literal, tolerating the same suffix forms (e.g. 5u).
    m = re.match(r"^(-?\d+)[uUlL]*$", expr)
    if m:
        return int(m.group(1))
    # Bit-shift literal: 1 << N, optionally wrapped in parentheses (e.g. (1 << 4)).
    m = re.match(r"^\(?\s*1\s*<<\s*(\d+)\s*\)?$", expr)
    if m:
        return 1 << int(m.group(1))
    # Reference to a previously-seen member (alias) — skip
    if expr in member_map:
        return None
    # Anything else (bitwise OR, complex expression) — skip
    return None


def parse_enum_body(body: str) -> list:
    """Parse the interior of an enum block and return (name, int_value) pairs.

    Skips sentinels, deprecated members, duplicate integer values (aliases),
    and members whose value expression cannot be evaluated statically.
    """
    results = []
    seen_values: set = set()
    member_map: dict = {}
    counter = 0

    # Remove all block comments (/* ... */) including multi-line ones before
    # processing line by line. This handles /** Docs spanning multiple lines */
    # patterns that appear after member values in this file.
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)

    for line in body.splitlines():
        line = re.sub(r"//.*", "", line).strip().rstrip(",")
        if not line:
            continue

        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*(?:=\s*(.+))?$", line)
        if not m:
            continue

        name = m.group(1)
        value_str = (m.group(2) or "").strip()

        if value_str:
            val = _eval_value(value_str, member_map)
            if val is None:
                continue  # alias or complex — skip without advancing counter
            counter = val
        else:
            val = counter

        counter = val + 1
        member_map[name] = val

        if _SENTINEL_RE.search(name):
            continue
        if _DEPRECATED_RE.search(name):
            continue
        if val in seen_values:
            continue  # duplicate value (alias) — keep first occurrence

        seen_values.add(val)
        results.append((name, val))

    return results


def _find_raw_enum_body(content: str, c_name: str) -> Optional[str]:
    """Return the raw text between the braces of a named enum block, or None."""
    pattern = (
        rf"enum\s+(?:class\s+)?{re.escape(c_name)}"
        rf"\s*(?::[^{{]+?)?\s*\{{(.*?)\}}"
    )
    m = re.search(pattern, content, re.DOTALL)
    return m.group(1) if m else None


def extract_named_enum(content: str, c_name: str) -> Optional[list]:
    """Find a named enum block (enum [class] c_name [: BaseType] { ... }) and parse it."""
    body = _find_raw_enum_body(content, c_name)
    return parse_enum_body(body) if body is not None else None


def extract_member_comments(raw_body: str) -> dict:
    """Extract inline or leading comments for enum member declarations.

    Handles three inline styles:
      MEMBER = v,  ///< text       (continuation lines also start with ///<)
      MEMBER = v,  /**< text */    (closing */ may be on the next line)
      MEMBER = v,  // text
    And one leading style:
      /* text */
      MEMBER = v,

    Returns {c_member_name: comment_text}.
    """
    comments: dict = {}
    lines = raw_body.splitlines()
    n = len(lines)
    pending: Optional[str] = None  # leading block comment waiting for a member
    i = 0

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # ---- member declaration? ----
        mem_m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)', stripped)
        if not mem_m:
            # Not a member line — check for a leading block comment.
            if stripped.startswith('/*'):
                # Read the whole comment (single- or multi-line).
                text_parts: list = []
                after_open = re.sub(r'^/\*+[!<]?\s*', '', stripped)
                close_m = re.search(r'(.*?)\*/', after_open)
                if close_m:
                    t = close_m.group(1).strip()
                    if t:
                        text_parts.append(t)
                else:
                    if after_open.strip():
                        text_parts.append(after_open.strip())
                    i += 1
                    while i < n:
                        cont = lines[i].strip()
                        end_m = re.search(r'(.*?)\*/', cont)
                        if end_m:
                            t = end_m.group(1).lstrip('*').strip()
                            if t:
                                text_parts.append(t)
                            i += 1
                            break
                        else:
                            t = cont.lstrip('*').strip()
                            if t:
                                text_parts.append(t)
                            i += 1
                pending = ' '.join(text_parts) if text_parts else None
            else:
                pending = None
            i += 1
            continue

        # ---- member line — look for inline comment ----
        member_name = mem_m.group(1)
        comment: Optional[str] = None

        triple_m = re.search(r'///<\s*(.*)', line)
        block_m = re.search(r'/\*+<\s*(.*)', line)
        plain_m = re.search(r'//(?![/<])\s*(.*)', line)

        if triple_m:
            text = triple_m.group(1).rstrip()
            j = i + 1
            while j < n:
                cont_m = re.match(r'^\s*///<\s*(.*)', lines[j])
                if cont_m:
                    text += ' ' + cont_m.group(1).strip()
                    j += 1
                else:
                    break
            comment = text.strip()
            i = j
        elif block_m:
            after = block_m.group(1)
            end = re.search(r'(.*?)\*/', after)
            if end:
                comment = end.group(1).strip()
                i += 1
            else:
                text = after.strip()
                j = i + 1
                while j < n:
                    end_m = re.search(r'(.*?)\*/', lines[j])
                    if end_m:
                        part = end_m.group(1).lstrip('*').strip()
                        if part:
                            text += ' ' + part
                        j += 1
                        break
                    else:
                        part = lines[j].strip().lstrip('*').strip()
                        if part:
                            text += ' ' + part
                        j += 1
                comment = text.strip()
                i = j
        elif plain_m:
            comment = plain_m.group(1).strip()
            i += 1
        elif pending:
            comment = pending
            i += 1
        else:
            i += 1

        if comment:
            comments[member_name] = comment
        pending = None

    return comments


def extract_prefixed_member_comments(content: str, prefix: str) -> dict:
    """Extract leading or inline block comments for prefix-matched enum members.

    Used for anonymous enums such as SlangTargetFlags where the members are not
    inside a named enum block and carry leading /* ... */ comments.
    Returns {c_member_name: comment_text}.
    """
    comments: dict = {}
    lines = content.splitlines()
    n = len(lines)
    pending: Optional[str] = None
    i = 0

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # Check for prefix-matched member
        line_clean = re.sub(r"//.*", "", line).strip().rstrip(",")
        mem_m = re.match(rf'^({re.escape(prefix)}[A-Za-z0-9_]+)\s*=', line_clean)
        if mem_m:
            member_name = mem_m.group(1)
            # Prefer inline comment; fall back to pending leading comment.
            triple_m = re.search(r'///<\s*(.*)', line)
            block_inline = re.search(r'/\*+<\s*(.*)', line)
            plain_m = re.search(r'//(?![/<])\s*(.*)', line)
            if triple_m:
                comments[member_name] = triple_m.group(1).strip()
            elif block_inline:
                after = block_inline.group(1)
                end = re.search(r'(.*?)\*/', after)
                if end:
                    comments[member_name] = end.group(1).strip()
            elif plain_m:
                comments[member_name] = plain_m.group(1).strip()
            elif pending:
                comments[member_name] = pending
            pending = None
            i += 1
            continue

        # Leading block comment
        if stripped.startswith('/*'):
            text_parts: list = []
            after_open = re.sub(r'^/\*+[!<]?\s*', '', stripped)
            close_m = re.search(r'(.*?)\*/', after_open)
            if close_m:
                t = close_m.group(1).strip()
                if t:
                    text_parts.append(t)
            else:
                if after_open.strip():
                    text_parts.append(after_open.strip())
                i += 1
                while i < n:
                    end_m = re.search(r'(.*?)\*/', lines[i].strip())
                    if end_m:
                        t = end_m.group(1).lstrip('*').strip()
                        if t:
                            text_parts.append(t)
                        i += 1
                        break
                    else:
                        t = lines[i].strip().lstrip('*').strip()
                        if t:
                            text_parts.append(t)
                        i += 1
            pending = ' '.join(text_parts) if text_parts else None
            i += 1
            continue

        pending = None
        i += 1

    return comments


def extract_prefixed_members(content: str, prefix: str) -> list:
    """Find all 'PREFIX_name = simple_value' lines anywhere in the file.

    Used for SlangTargetFlags, which is declared as an anonymous enum after
    a typedef rather than as a named enum.
    """
    results = []
    seen_values: set = set()

    for line in content.splitlines():
        line_clean = re.sub(r"//.*", "", line).strip().rstrip(",")
        m = re.match(
            rf"^({re.escape(prefix)}[A-Za-z0-9_]+)\s*=\s*(.+)$", line_clean
        )
        if not m:
            continue
        name = m.group(1)
        val_str = m.group(2).strip()
        val = _eval_value(val_str, {})
        if val is None:
            continue
        if _SENTINEL_RE.search(name):
            continue
        if _DEPRECATED_RE.search(name):
            continue
        if val in seen_values:
            continue
        seen_values.add(val)
        results.append((name, val))

    return results


# ---------------------------------------------------------------------------
# Prefix stripping
# ---------------------------------------------------------------------------


def strip_prefix(names: list, forced_prefix: Optional[str]) -> tuple:
    """Determine and strip the common name prefix from a list of C member names.

    Returns (detected_prefix, list_of_stripped_names).

    forced_prefix="" → keep names unchanged (CompilerOptionName: already PascalCase).
    forced_prefix="FOO_" → strip that exact prefix from every name.
    forced_prefix=None → auto-detect the longest common prefix ending with '_'.
    """
    if forced_prefix == "":
        return ("", list(names))
    if forced_prefix:
        stripped = [
            n[len(forced_prefix):] if n.startswith(forced_prefix) else n
            for n in names
        ]
        return (forced_prefix, stripped)
    # Auto-detect
    if not names:
        return ("", list(names))
    common = os.path.commonprefix(names)
    idx = common.rfind("_")
    prefix = common[: idx + 1] if idx >= 0 else ""
    stripped = [n[len(prefix):] if n.startswith(prefix) else n for n in names]
    return (prefix, stripped)


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_GENERATED_HEADER = (
    "// THIS FILE IS GENERATED — DO NOT EDIT.\n"
    "// Source: include/slang.h\n"
    "// Generator: source/slang-wasm-wasi/tools/generate-slang-bindings.py\n"
    "// Re-run: python source/slang-wasm-wasi/tools/generate-slang-bindings.py  (or cmake --preset default)\n"
)


def generate_cpp(enum_data: dict) -> str:
    """Emit slang-wasm-wasi-enum-generated.cpp.

    The file exports two C functions from the WASM module:
      slang_wasm_enum_metadata_ptr() → pointer to the JSON blob in linear memory
      slang_wasm_enum_metadata_len() → byte length of the blob (excluding NUL)

    The JSON format is: {"EnumName":{"MemberName":intValue,...},...}
    Each enum occupies one C string literal line so the file stays readable.
    """
    # Build one C string literal per enum so the file is readable.
    # Each fragment represents the JSON substring: "EnumName":{"A":1,"B":2,...}
    # json.dumps() of that substring escapes the inner quotes for us.
    fragments = []
    for name, members in enum_data.items():
        inner = json.dumps(dict(members), separators=(",", ":"))
        substring = f"{json.dumps(name)}:{inner}"   # e.g. "Target":{"SPIRV":6,...}
        fragments.append(json.dumps(substring))      # C string literal with escapes

    # Assemble: "{" <frag0> "," <frag1> ... "}"
    string_lines = ['    "{"']
    for i, frag in enumerate(fragments):
        if i > 0:
            string_lines.append('    ","')
        string_lines.append(f"    {frag}")
    string_lines.append('    "}";')

    lines = [
        _GENERATED_HEADER,
        "",
        '#include "slang-wasm-wasi.h"',
        "",
        "#include <cstdint>",
        "",
        "// clang-format off",
        "static const char kEnumMetadataJson[] =",
        *string_lines,
        "// clang-format on",
        "",
        'extern "C" uint32_t slang_wasm_enum_metadata_ptr(void) {',
        "    return static_cast<uint32_t>(",
        "        reinterpret_cast<uintptr_t>(kEnumMetadataJson));",
        "}",
        'extern "C" uint32_t slang_wasm_enum_metadata_len(void) {',
        "    return static_cast<uint32_t>(sizeof(kEnumMetadataJson) - 1);",
        "}",
        "",
    ]
    return "\n".join(lines)


def generate_java_enum(spec: EnumSpec, java_members: list, comments: dict, package: str) -> str:
    """Emit a Java enum source file for one Slang enum.

    comments maps each Java member name to a Javadoc string (may be empty).
    package is the Java package the generated enum is declared in, e.g.
    "org.shaderslang.wasm.enums". The enum is annotated with
    javax.annotation.processing.Generated so IDEs and static-analysis tools
    (e.g. code coverage, "find usages") recognize it as generated code and
    exclude it from the checks that apply to hand-written sources.
    """
    # One constant per line; all but the last end with a comma, the last with a semicolon.
    member_lines = []
    for i, (name, value) in enumerate(java_members):
        suffix = "," if i < len(java_members) - 1 else ";"
        if name in comments:
            member_lines.append(f"    /** {comments[name]} */")
        member_lines.append(f"    {name}({value}){suffix}")

    lines = [
        _GENERATED_HEADER,
        "",
        f"package {package};",
        "",
        "import javax.annotation.processing.Generated;",
        "",
        f"/** {spec.javadoc} Mirrors {{@code {spec.c_name}}} in slang.h. */",
        '@Generated("source/slang-wasm-wasi/tools/generate-slang-bindings.py")',
        f"public enum {spec.java_name} {{",
        *member_lines,
        "",
        "    public final int value;",
        "",
        f"    {spec.java_name}(int value) {{",
        "        this.value = value;",
        "    }",
        "",
        f"    /** Return the {spec.java_name} constant for the given integer value. */",
        f"    public static {spec.java_name} fromValue(int v) {{",
        f"        for ({spec.java_name} t : values()) if (t.value == v) return t;",
        f'        throw new IllegalArgumentException("Unknown {spec.java_name} value: " + v);',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    repo_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    )

    parser = argparse.ArgumentParser(description="Generate Slang enum bindings.")
    parser.add_argument(
        "--slang-h",
        default=os.path.join(repo_root, "include", "slang.h"),
        help="Path to include/slang.h",
    )
    parser.add_argument(
        "--cpp-out",
        default=os.path.join(
            repo_root,
            "source", "slang-wasm-wasi", "slang-wasm-wasi-enum-generated.cpp",
        ),
        help="Output path for the C++ metadata translation unit",
    )
    parser.add_argument(
        "--java-out",
        default=None,
        help=(
            "Output directory for generated Java enum source files. "
            "Omit to skip Java generation (the default)."
        ),
    )
    parser.add_argument(
        "--java-package",
        default="org.shaderslang.wasm.enums",
        help="Java package declared in the generated enum source files",
    )
    args = parser.parse_args()

    with open(args.slang_h, encoding="utf-8") as f:
        content = f.read()

    # Collect per-enum (java_name → [(java_member_name, int_value)]) data.
    enum_data: dict = {}
    enum_comments: dict = {}  # java_name → {java_member_name: comment_text}

    for spec in ENUM_CONFIG:
        # Extract raw (C_member_name, int_value) pairs.
        if spec.prefix:
            # Anonymous or flag enum: locate members by their name prefix.
            raw = extract_prefixed_members(content, spec.prefix)
            raw_comments = extract_prefixed_member_comments(content, spec.prefix)
        else:
            # Named enum (covers both "enum class" and "enum Name : Base").
            raw = extract_named_enum(content, spec.c_name)
            raw_body = _find_raw_enum_body(content, spec.c_name)
            raw_comments = extract_member_comments(raw_body) if raw_body else {}

        if raw is None:
            print(
                f"WARNING: enum {spec.c_name!r} not found in {args.slang_h}",
                file=sys.stderr,
            )
            continue
        if not raw:
            print(
                f"WARNING: enum {spec.c_name!r} has no parseable members",
                file=sys.stderr,
            )
            continue

        c_names = [n for n, _ in raw]
        values = [v for _, v in raw]
        _, stripped = strip_prefix(c_names, spec.prefix)
        enum_data[spec.java_name] = list(zip(stripped, values))

        # Map stripped Java names → comments, skipping members with no comment.
        java_comments: dict = {}
        for c_name, java_name in zip(c_names, stripped):
            if c_name in raw_comments:
                java_comments[java_name] = raw_comments[c_name]
        enum_comments[spec.java_name] = java_comments

    # Write C++ output.
    cpp_dir = os.path.dirname(args.cpp_out)
    if cpp_dir:
        os.makedirs(cpp_dir, exist_ok=True)
    with open(args.cpp_out, "w", encoding="utf-8") as f:
        f.write(generate_cpp(enum_data))
    print(f"Wrote {args.cpp_out}")

    # Write Java outputs only when explicitly requested via --java-out.
    if args.java_out:
        os.makedirs(args.java_out, exist_ok=True)
        for spec in ENUM_CONFIG:
            if spec.java_name not in enum_data:
                continue
            java_source = generate_java_enum(
                spec,
                enum_data[spec.java_name],
                enum_comments.get(spec.java_name, {}),
                args.java_package,
            )
            out_path = os.path.join(args.java_out, f"{spec.java_name}.java")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(java_source)
            print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
