export let demoList = [
  { name: "Simple Print", url: "simple-print.slang" },
  { name: "Simple Image", url: "simple-image.slang" },
  { name: "Image From URL", url: "image-from-url.slang" },
  { name: "Multi-kernel Demo", url: "multiple-kernels.slang" },
  { name: "──────────", url: "" },
  { name: "ShaderToy: Circle", url: "circle.slang" },
  { name: "ShaderToy: Ocean", url: "ocean.slang" },
  { name: "Painting", url: "painting.slang" },
  { name: "2D Splatter", url: "gsplat2d.slang" },
  { name: "Differentiable 2D Splatter", url: "gsplat2d-diff.slang" },
  { name: "──────────", url: "" },
  { name: "Properties", url: "property.slang" },
  { name: "Generics & Extensions", url: "generic.slang" },
  { name: "Operator Overload", url: "operator-overload.slang" },
  { name: "Variadic Generics", url: "variadic.slang" },
  { name: "Automatic Differentiation", url: "autodiff.slang" },
  { name: "Graphics Entrypoints", url: "entrypoint.slang" },
  { name: "Atomics", url: "atomics.slang" },
  { name: "Lambda Expressions", url: "lambda.slang" },
];
