// Hash function for GLSLstd450
//
// This file was thoughtfully generated by a machine,
// don't even think about modifying it yourself!
//

#include "../core/slang-common.h"
#include "../core/slang-string.h"
#include "spirv/unified1/GLSL.std.450.h"


namespace Slang
{

bool lookupGLSLstd450(const UnownedStringSlice& str, GLSLstd450& value)
{
    static const unsigned tableSalt[81] = {
        0, 1, 1, 8, 3, 0, 3, 0, 1, 1, 4, 0, 6, 7, 0, 0,
        0, 2, 0, 2, 0, 0, 0, 10, 1, 0, 1, 6, 0, 5, 6, 0,
        1, 11, 0, 2, 6, 0, 1, 4, 15, 0, 0, 2, 0, 4, 0, 2,
        4, 6, 0, 0, 5, 0, 0, 1, 3, 9, 16, 5, 0, 75, 0, 0,
        10, 0, 1, 67, 7, 1, 15, 0, 0, 4, 4, 10, 20, 0, 0, 4,
        14
    };

    using KV = std::pair<const char*, GLSLstd450>;

    static const KV words[81] =
    {
        {"InterpolateAtOffset", GLSLstd450InterpolateAtOffset},
        {"Modf", GLSLstd450Modf},
        {"Determinant", GLSLstd450Determinant},
        {"NClamp", GLSLstd450NClamp},
        {"PackSnorm2x16", GLSLstd450PackSnorm2x16},
        {"PackSnorm4x8", GLSLstd450PackSnorm4x8},
        {"UMax", GLSLstd450UMax},
        {"SClamp", GLSLstd450SClamp},
        {"UnpackSnorm4x8", GLSLstd450UnpackSnorm4x8},
        {"Trunc", GLSLstd450Trunc},
        {"PackUnorm4x8", GLSLstd450PackUnorm4x8},
        {"Exp2", GLSLstd450Exp2},
        {"InterpolateAtCentroid", GLSLstd450InterpolateAtCentroid},
        {"Tan", GLSLstd450Tan},
        {"Log", GLSLstd450Log},
        {"SMax", GLSLstd450SMax},
        {"IMix", GLSLstd450IMix},
        {"SMin", GLSLstd450SMin},
        {"FindUMsb", GLSLstd450FindUMsb},
        {"Cosh", GLSLstd450Cosh},
        {"UnpackSnorm2x16", GLSLstd450UnpackSnorm2x16},
        {"Asin", GLSLstd450Asin},
        {"ModfStruct", GLSLstd450ModfStruct},
        {"NMin", GLSLstd450NMin},
        {"MatrixInverse", GLSLstd450MatrixInverse},
        {"Reflect", GLSLstd450Reflect},
        {"UMin", GLSLstd450UMin},
        {"FSign", GLSLstd450FSign},
        {"Log2", GLSLstd450Log2},
        {"Sinh", GLSLstd450Sinh},
        {"Length", GLSLstd450Length},
        {"FMax", GLSLstd450FMax},
        {"NMax", GLSLstd450NMax},
        {"SSign", GLSLstd450SSign},
        {"RoundEven", GLSLstd450RoundEven},
        {"UnpackUnorm4x8", GLSLstd450UnpackUnorm4x8},
        {"Atanh", GLSLstd450Atanh},
        {"Ldexp", GLSLstd450Ldexp},
        {"InverseSqrt", GLSLstd450InverseSqrt},
        {"Exp", GLSLstd450Exp},
        {"Degrees", GLSLstd450Degrees},
        {"Atan", GLSLstd450Atan},
        {"Acosh", GLSLstd450Acosh},
        {"Distance", GLSLstd450Distance},
        {"Ceil", GLSLstd450Ceil},
        {"Asinh", GLSLstd450Asinh},
        {"Sin", GLSLstd450Sin},
        {"Fract", GLSLstd450Fract},
        {"Radians", GLSLstd450Radians},
        {"UnpackDouble2x32", GLSLstd450UnpackDouble2x32},
        {"Step", GLSLstd450Step},
        {"Atan2", GLSLstd450Atan2},
        {"UnpackUnorm2x16", GLSLstd450UnpackUnorm2x16},
        {"UClamp", GLSLstd450UClamp},
        {"FAbs", GLSLstd450FAbs},
        {"PackHalf2x16", GLSLstd450PackHalf2x16},
        {"PackDouble2x32", GLSLstd450PackDouble2x32},
        {"SmoothStep", GLSLstd450SmoothStep},
        {"UnpackHalf2x16", GLSLstd450UnpackHalf2x16},
        {"FClamp", GLSLstd450FClamp},
        {"Cos", GLSLstd450Cos},
        {"Tanh", GLSLstd450Tanh},
        {"Round", GLSLstd450Round},
        {"FindSMsb", GLSLstd450FindSMsb},
        {"Frexp", GLSLstd450Frexp},
        {"Normalize", GLSLstd450Normalize},
        {"Floor", GLSLstd450Floor},
        {"Cross", GLSLstd450Cross},
        {"FMix", GLSLstd450FMix},
        {"FaceForward", GLSLstd450FaceForward},
        {"Refract", GLSLstd450Refract},
        {"FMin", GLSLstd450FMin},
        {"FrexpStruct", GLSLstd450FrexpStruct},
        {"SAbs", GLSLstd450SAbs},
        {"PackUnorm2x16", GLSLstd450PackUnorm2x16},
        {"FindILsb", GLSLstd450FindILsb},
        {"InterpolateAtSample", GLSLstd450InterpolateAtSample},
        {"Acos", GLSLstd450Acos},
        {"Fma", GLSLstd450Fma},
        {"Pow", GLSLstd450Pow},
        {"Sqrt", GLSLstd450Sqrt},
    };

    static const auto hash = [](const UnownedStringSlice& str, UInt32 salt){
        return combineHash(getHashCode(str), getHashCode(salt)) % 81;
    };

    const auto i = hash(str, tableSalt[hash(str, 0)]);
    if(str == words[i].first)
    {
        value = words[i].second;
        return true;
    }
    else
    {
        return false;
    }
}

}
