# Windows Runner Startup Script
#
# This script runs when a new ephemeral Windows GPU VM boots. It:
# 1. Removes any pre-existing runner service from the base image
# 2. Updates the preinstalled GitHub Actions runner if its version differs
#    from $RunnerVersion (no-op when the image is already up to date)
# 3. Reads the JIT (just-in-time) runner config from GCP instance metadata
# 4. Configures the GitHub Actions runner with the JIT config
# 5. Runs the runner (executes one job, then exits)
# 6. Shuts down the VM (so the scaler can delete it)
#
# The JIT config is a base64-encoded blob generated by the Scale Set Client
# that contains everything the runner needs to register with GitHub.

$ErrorActionPreference = "Stop"

$runnerDir = "C:\actions-runner"
$logFile = "C:\actions-runner\startup.log"

# When this version differs from the runner binary baked into the GCP image,
# the script downloads and extracts the matching release before registration.
# Bumping this constant + redeploying the scaler is enough to roll out a new
# runner version without rebuilding the GCP image. Image rebakes are an
# optimization to skip the per-boot download cost.
$RunnerVersion = "2.334.0"
$RunnerSha256 = "a0c896f3acf37841cc17f392a38111d39501e56f2990434567f027ee89cf8981"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "$timestamp - $Message"
    Write-Host $line
    Add-Content -Path $logFile -Value $line
}

function Stop-WithFailure {
    param([string]$Message, [string]$ArchivePath)
    Write-Log "ERROR: $Message"
    if ($ArchivePath -and (Test-Path $ArchivePath)) {
        Remove-Item $ArchivePath -Force -ErrorAction SilentlyContinue
    }
    Stop-Computer -Force
    exit 1
}

function Get-InstalledRunnerVersion {
    $listener = Join-Path $runnerDir "bin\Runner.Listener.exe"
    if (-not (Test-Path $listener)) {
        return $null
    }
    try {
        # Match the Linux side (PR #10995) by invoking Runner.Listener directly.
        # run.cmd would also work but pulls in the cmd shell wrapper.
        $output = & $listener --version 2>$null
        if ($LASTEXITCODE -ne 0) {
            return $null
        }
        $line = ($output | Where-Object { $_ -match '\S' } | Select-Object -First 1)
        if (-not $line) {
            return $null
        }
        return $line.ToString().Trim()
    }
    catch {
        return $null
    }
}

Write-Log "=== Windows GPU Runner Startup ==="

# Step 0: Remove any pre-existing runner service from the base image.
# The base image was snapshotted from a static runner that has the runner
# agent configured as a Windows service with old credentials. We need to
# stop and remove it before configuring with JIT config.
Write-Log "Removing pre-existing runner service (if any)..."
try {
    Set-Location $runnerDir
    $svc = Get-Service -Name "actions.runner.*" -ErrorAction SilentlyContinue
    if ($svc) {
        Write-Log "  Found service: $($svc.Name) (Status: $($svc.Status))"
        Stop-Service -Name $svc.Name -Force -ErrorAction SilentlyContinue
        & .\svc.cmd uninstall 2>&1 | ForEach-Object { Write-Log "  $_" }
        Write-Log "  Service removed."
    } else {
        Write-Log "  No existing runner service found."
    }
    # Also remove any existing runner config (.runner file)
    if (Test-Path "$runnerDir\.runner") {
        Remove-Item "$runnerDir\.runner" -Force
        Remove-Item "$runnerDir\.credentials" -Force -ErrorAction SilentlyContinue
        Remove-Item "$runnerDir\.credentials_rsaparams" -Force -ErrorAction SilentlyContinue
        Write-Log "  Removed old runner configuration files."
    }
}
catch {
    Write-Log "  WARNING: Failed to remove existing service: $_"
}

# Step 0.5: Update the runner binary if the image has a stale version.
# When the baked binary already matches $RunnerVersion this is a sub-second
# version-check no-op; only mismatched versions pay the download cost.
$installedRunnerVersion = Get-InstalledRunnerVersion
if (-not $installedRunnerVersion) {
    $installedRunnerVersion = "unknown"
}
Write-Log "Current Actions runner version: $installedRunnerVersion"

if ($installedRunnerVersion -ne $RunnerVersion) {
    Write-Log "Updating Actions runner to v${RunnerVersion}..."
    $runnerArchive = Join-Path $env:TEMP ("actions-runner-{0}.zip" -f ([guid]::NewGuid().ToString("N")))
    $runnerUrl = "https://github.com/actions/runner/releases/download/v${RunnerVersion}/actions-runner-win-x64-${RunnerVersion}.zip"

    # Retry the download a few times to tolerate transient network errors,
    # mirroring the curl --retry 3 behaviour on the Linux side.
    $downloadAttempts = 3
    $downloadOk = $false
    for ($attempt = 1; $attempt -le $downloadAttempts; $attempt++) {
        try {
            Invoke-WebRequest -Uri $runnerUrl -OutFile $runnerArchive -UseBasicParsing -TimeoutSec 120
            $downloadOk = $true
            break
        }
        catch {
            Write-Log "  Download attempt ${attempt}/${downloadAttempts} failed: $_"
            if ($attempt -lt $downloadAttempts) {
                Start-Sleep -Seconds 5
            }
        }
    }
    if (-not $downloadOk) {
        Stop-WithFailure "Failed to download Actions runner v${RunnerVersion} after ${downloadAttempts} attempts" $runnerArchive
    }

    try {
        $actualHash = (Get-FileHash -Path $runnerArchive -Algorithm SHA256).Hash.ToLowerInvariant()
    }
    catch {
        Stop-WithFailure "Failed to hash Actions runner v${RunnerVersion}: $_" $runnerArchive
    }

    $expectedHash = $RunnerSha256.ToLowerInvariant()
    if ($actualHash -ne $expectedHash) {
        Stop-WithFailure "Actions runner v${RunnerVersion} checksum verification failed (expected ${RunnerSha256}, got ${actualHash})" $runnerArchive
    }

    try {
        Expand-Archive -Path $runnerArchive -DestinationPath $runnerDir -Force
    }
    catch {
        Stop-WithFailure "Failed to extract Actions runner v${RunnerVersion}: $_" $runnerArchive
    }

    Remove-Item $runnerArchive -Force -ErrorAction SilentlyContinue

    $updatedRunnerVersion = Get-InstalledRunnerVersion
    Write-Log "Actions runner version after update: $(if ($updatedRunnerVersion) { $updatedRunnerVersion } else { 'unknown' })"
    if ($updatedRunnerVersion -ne $RunnerVersion) {
        Stop-WithFailure "Runner version mismatch after update (expected ${RunnerVersion}, got $(if ($updatedRunnerVersion) { $updatedRunnerVersion } else { 'unknown' }))"
    }
}

# Step 1: Read JIT config from GCP instance metadata
Write-Log "Reading JIT config from instance metadata..."
$metadataUrl = "http://metadata.google.internal/computeMetadata/v1/instance/attributes/jit-config"
$maxRetries = 10
$jitConfig = $null

for ($i = 1; $i -le $maxRetries; $i++) {
    try {
        $jitConfig = Invoke-RestMethod -Uri $metadataUrl -Headers @{ "Metadata-Flavor" = "Google" } -TimeoutSec 10
        break
    }
    catch {
        Write-Log "  Attempt ${i}/${maxRetries}: Metadata not available yet, waiting..."
        Start-Sleep -Seconds 5
    }
}

if (-not $jitConfig) {
    Write-Log "ERROR: Failed to read JIT config from metadata after $maxRetries attempts"
    Stop-Computer -Force
    exit 1
}

Write-Log "JIT config retrieved ($($jitConfig.Length) chars)"

# Step 2: Log GPU and system info
Write-Log "=== System Information ==="
try {
    nvidia-smi 2>&1 | ForEach-Object { Write-Log "  $_" }
}
catch {
    Write-Log "WARNING: nvidia-smi not available"
}

# Step 3: Start sccache server (for build caching)
Write-Log "Starting sccache server..."
try {
    sccache --start-server 2>&1 | ForEach-Object { Write-Log "  $_" }
}
catch {
    Write-Log "WARNING: sccache start failed (builds will be uncached)"
}

# Step 3.5: Configure git safe directory to avoid "dubious ownership" errors.
# The runner runs as SYSTEM but the workspace may be owned by NETWORK SERVICE.
Write-Log "Configuring git safe directory..."
git config --global --add safe.directory '*'

# Step 4: Configure and run the GitHub Actions runner with JIT config
Write-Log "Starting runner with JIT config..."
Set-Location $runnerDir

try {
    # The --jitconfig flag configures and runs the runner in one step.
    # In ephemeral mode, it runs exactly one job and then exits.
    & .\run.cmd --jitconfig $jitConfig
    $exitCode = $LASTEXITCODE
    Write-Log "Runner exited with code $exitCode"
}
catch {
    Write-Log "ERROR: Runner failed: $_"
    $exitCode = 1
}

# Step 5: Stop sccache and show stats
Write-Log "=== sccache stats ==="
try {
    sccache --show-stats 2>&1 | ForEach-Object { Write-Log "  $_" }
    sccache --stop-server 2>&1 | Out-Null
}
catch {
    Write-Log "WARNING: sccache stats unavailable"
}

# Step 6: Shut down the VM
# The scaler's cleanup loop will detect the TERMINATED state and delete the VM.
Write-Log "=== Runner complete, shutting down VM ==="
Stop-Computer -Force
