function(auto_option name package description)
    set(${name} "AUTO" CACHE STRING ${description})
    set_property(CACHE ${name} PROPERTY STRINGS AUTO ON OFF)

    if(${name} OR ${name} STREQUAL "AUTO")
        if(${name} STREQUAL "AUTO")
            set(req)
        else()
            set(req REQUIRED)
        endif()
        find_package(${package} ${req})
        if(${${package}_FOUND})
            set(${name} TRUE CACHE STRING ${description} FORCE)
        else(NOT ${${package}_FOUND})
            set(${name} FALSE CACHE STRING ${description} FORCE)
        endif()
    endif()
endfunction()
