"""Regenerate the hermetic LLVM 14 NVVM bitcode fixture header."""

from hashlib import sha256
from pathlib import Path

import llvmlite
from llvmlite import binding as llvm


LLVMLITE_VERSION = "0.42.0"
LLVM_VERSION = (14, 0, 6)
EXPECTED_SIZE = 1668
EXPECTED_SHA256 = "b45e3b74a3881b178c3d45310cc74d0bed3ece46e7101e6b9ac98a66aa301f01"


def main() -> None:
    if llvmlite.__version__ != LLVMLITE_VERSION:
        raise RuntimeError(
            f"expected llvmlite {LLVMLITE_VERSION}, found {llvmlite.__version__}"
        )
    if llvm.llvm_version_info != LLVM_VERSION:
        raise RuntimeError(f"expected LLVM {LLVM_VERSION}, found {llvm.llvm_version_info}")

    fixture_dir = Path(__file__).resolve().parent
    source_path = fixture_dir / "minimal-empty-kernel.ll"
    header_path = fixture_dir.parents[1] / "unit-test-nvvm-bitcode-fixture.h"

    module = llvm.parse_assembly(source_path.read_text(encoding="utf-8"))
    module.verify()
    if "void ()* @testEmpty" not in str(module):
        raise RuntimeError("fixture producer did not preserve the required typed function pointer")

    bitcode = module.as_bitcode()
    digest = sha256(bitcode).hexdigest()
    if not bitcode.startswith(bytes.fromhex("42 43 c0 de")):
        raise RuntimeError("fixture does not start with LLVM bitcode magic")
    if len(bitcode) != EXPECTED_SIZE or digest != EXPECTED_SHA256:
        raise RuntimeError(
            f"unexpected fixture: {len(bitcode)} bytes, SHA-256 {digest}; "
            "update the reviewed provenance before accepting a new fixture"
        )

    byte_lines = []
    for offset in range(0, len(bitcode), 12):
        values = ", ".join(f"0x{value:02x}" for value in bitcode[offset : offset + 12])
        byte_lines.append(f"    {values},")

    header = "\n".join(
        [
            "// Generated by LLVM 14.0.6 from test-data/nvvm/minimal-empty-kernel.ll.",
            "// See test-data/nvvm/README.md for provenance and regeneration instructions.",
            "",
            "#ifndef SLANG_UNIT_TEST_NVVM_BITCODE_FIXTURE_H",
            "#define SLANG_UNIT_TEST_NVVM_BITCODE_FIXTURE_H",
            "",
            "static const uint8_t kMinimalNVVMBitcode[] = {",
            *byte_lines,
            "};",
            "",
            "#endif",
            "",
        ]
    )
    with header_path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(header)


if __name__ == "__main__":
    main()
