"""Deterministic, size-scalable Slang workload generators for the compile-time
perf suite.

Each generator is a function ``gen(n) -> dict[str, str]`` mapping a filename to
Slang source. Most workloads are a single file; the module-link workload emits
several. Generators must be deterministic (same ``n`` -> identical bytes) so a
release sweep compares like with like.

Conventions:
- Every compilable workload exposes a ``[shader("compute")]`` entry named
  ``computeMain`` so ``slangc`` auto-discovers it; results are written to a
  ``RWStructuredBuffer`` so nothing is dead-code-eliminated.
"""

import os

# ASCII only: generated sources must be byte-identical on every platform
# (Windows CI writes them with a legacy default codec unless told otherwise,
# and slangc reads bytes as UTF-8), so no typographic characters here.
_HEADER = "// AUTO-GENERATED by perf-suite/workloads.py - do not edit by hand.\n"
_CORPUS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "corpus")

# "Scaling null:" convention — each swept generator's docstring ends with a
# one-line scaling null: the IDEAL asymptotic cost of the workload in its size
# knob n, i.e. the hypothesis the sweep tests against. A sweep exponent
# meaningfully above the null (see sweep_report's super-linearity flags) means
# the amplified pass scales worse than its input, which is the finding.
# complexity_ladder is marked "Scaling reference (not a null)" because it
# deliberately scales several dimensions together and has no single-pass ideal.


def _buf():
    """Standard output-buffer declaration used by every compilable workload.

    All workload generators write results into `outBuf` so that nothing is
    dead-code-eliminated before the targeted compiler stage runs.
    """
    return "RWStructuredBuffer<float> outBuf;\n\n"


# --------------------------------------------------------------------------- #
# Per-compile floor
# --------------------------------------------------------------------------- #

def gen_minimal(n):
    """Near-empty shader: isolates the fixed per-compile floor — core-module
    deserialization (readSerializedModuleIR/AST, loadBuiltinModule) plus linkIR
    of the user module against the core module — with negligible user-code work.

    This is the cleanest detector for "the standard library got heavier"
    regressions: when the core module grows, every compile pays here regardless
    of which language features it uses (the class of regression introduced by the
    auto-diff overhaul in PR #9808, where an empty shader's linkIR rose ~27x)."""
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID) { outBuf[tid.x] = float(tid.x); }\n")
    return {"minimal.slang": "".join(s)}


def gen_ir_builder(n):
    """One enormous straight-line function: `n` trivial integer SSA ops, almost
    no semantic work. Stresses IR instruction construction / dedup / hash-cons
    and the SSA simplifier (the shared IRBuilder layer PR #9808 touched).

    Scaling null: n scales straight-line op count; ideal cost is O(n) with amortized-constant hash-consing, so super-linear sweep growth means IR dedup/use-list structures scale worse than the code.
    """
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    int acc = int(tid.x);\n")
    for i in range(n):
        op = "*" if i % 3 == 0 else ("+" if i % 3 == 1 else "^")
        s.append(f"    acc = acc {op} {i % 13 + 1};\n")
    s.append("    outBuf[0] = float(acc);\n}\n")
    return {"ir_builder.slang": "".join(s)}


def gen_serialize(n):
    """A large module of `n` public functions, compiled to a .slang-module.
    Stresses IR/AST serialization (writeSerializedModule*) — the write side of
    the cost whose read side (readSerializedModule*) the `minimal` floor test
    and module loading exercise.

    Scaling null: n scales function count; ideal serialization cost is O(n).
    """
    s = [_HEADER]
    for i in range(n):
        s.append(
            f"public float sfn_{i}(float x, float y) {{ return x * {i % 7 + 1}.0 + y * {i % 5 + 1}.0 + sin(x + {i}.0); }}\n"
        )
    return {"serialize.slang": "".join(s)}


def gen_conformance(n):
    """`n` structs each conforming to a shared interface. Stresses interface
    conformance checking / witness synthesis in the front end (compiled to a
    .slang-module so the signal is sema, not codegen).

    Scaling null: n scales conforming structs against ONE interface; ideal checking cost is O(n).
    """
    s = [_HEADER]
    s.append("interface IFace { float f(float x); int g(); }\n\n")
    for i in range(n):
        s.append(
            f"struct C{i} : IFace {{ float f(float x) {{ return x * {i % 9 + 1}.0 + {i}.0; }} "
            f"int g() {{ return {i}; }} }}\n"
        )
    return {"conformance.slang": "".join(s)}


def gen_loop_unroll(n):
    """A force-unrolled loop of `n` iterations. Stresses loop unrolling
    (unrollLoopsInModule) and the downstream SSA simplify on the unrolled body.

    Scaling null: the unrolled output is O(n), so ideal cost is linear in n (linear in output size).
    """
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = outBuf[tid.x];\n")
    s.append(f"    [ForceUnroll] for (int i = 0; i < {n}; ++i)\n")
    s.append("        acc = acc * 1.0009 + sin(acc + float(i)) * 0.5 - cos(acc * 0.5);\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"loop_unroll.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Suspected-regression features
# --------------------------------------------------------------------------- #

# Call depth within a group. Work scales by *breadth* (number of groups), while
# nesting stays bounded so we don't hit the compiler's type-nesting recursion cap
# (~32 levels in practice). 8 gives ~4× margin and is empirically safe up to
# n=1280 (the largest sweep size used).
_GROUP_DEPTH = 8


def gen_autodiff(n):
    """n differentiable functions arranged in bounded-depth groups, each group
    differentiated in both forward and reverse mode, plus a differentiable
    generic. Stresses the autodiff IR transform (inside linkAndOptimizeIR) and
    the front-end checking of [Differentiable]. Scales by breadth.

    Scaling null: n scales group breadth with depth bounded by _GROUP_DEPTH, so ideal autodiff cost is O(n).
    """
    s = [_HEADER, _buf()]
    s.append("[Differentiable]\n")
    s.append("float leaf(float x) { return x * x + sin(x) * cos(x); }\n\n")
    group_tops = []
    for i in range(n):
        prev = "leaf" if (i % _GROUP_DEPTH == 0) else f"chain_{i - 1}"
        s.append("[Differentiable]\n")
        s.append(
            f"float chain_{i}(float x) {{ return {prev}(x) * 1.0009 + sin(x) * 0.5 - cos(x) * 0.25; }}\n"
        )
        if (i % _GROUP_DEPTH == _GROUP_DEPTH - 1) or i == n - 1:
            group_tops.append(i)
    s.append("\n")
    # A differentiable generic instantiated for float.
    s.append("[Differentiable]\n")
    s.append("T poly<T : IDifferentiable & IFloat>(T x) { return x * x * x + x; }\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float x = outBuf[tid.x];\n    float acc = 0.0;\n")
    for top in group_tops:
        s.append("    { var dp = diffPair(x, 1.0);\n")
        s.append(f"      bwd_diff(chain_{top})(dp, 1.0); acc += dp.d;\n")
        s.append(f"      acc += fwd_diff(chain_{top})(diffPair(x, 1.0)).d; }}\n")
    s.append("    acc += fwd_diff(poly<float>)(diffPair(x, 1.0)).d;\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"autodiff.slang": "".join(s)}


def gen_dynamic_dispatch(n):
    """One interface, n implementations, called through an existential whose
    concrete type is chosen at runtime (defeats static specialization, forcing
    witness-table dynamic dispatch). Stresses dispatch lowering / specializeModule.

    Scaling null: n scales implementations and switch cases; generated code is O(n), so ideal cost is O(n).
    """
    s = [_HEADER, _buf()]
    s.append("[anyValueSize(16)]\ninterface IShape { float eval(float x); }\n\n")
    for i in range(n):
        s.append(
            f"struct Shape{i} : IShape {{ float eval(float x) {{ return x * {i + 1}.0 + {i}.0 + sin(x * {i + 1}.0); }} }}\n"
        )
    s.append("\nfloat dispatch(int id, float x)\n{\n    IShape s;\n    switch (id)\n    {\n")
    for i in range(n):
        s.append(f"    case {i}: s = Shape{i}(); break;\n")
    s.append("    default: s = Shape0(); break;\n    }\n    return s.eval(x);\n}\n\n")
    s.append("float run(IShape s, float x) { return s.eval(x); }\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = 0.0;\n")
    s.append("    int base = int(tid.x);\n")
    s.append(f"    for (int i = 0; i < {n}; ++i)\n")
    s.append("        acc += dispatch((base + i) % " + str(n) + ", outBuf[0] + float(i));\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"dynamic_dispatch.slang": "".join(s)}


def gen_diagnostics_clean(n):
    """N functions with distinct compile-time constants, no errors.

    Scaling null: n scales independent declarations; ideal cost is O(n).
    """
    s = [_HEADER, _buf()]
    for i in range(n):
        s.append(f"static const float k_{i} = {i % 7}.0;\n")
        s.append(f"float ok_{i}(float x) {{ return x + k_{i} * {i % 5 + 1}.0; }}\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    s.append(f"    for (int i = 0; i < {n}; ++i) acc += ok_0(float(i));\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"diagnostics_clean.slang": "".join(s)}


def gen_existential_aggregate(n):
    """An interface-typed *field* inside a struct (`Scene { IMat m; ... }`), with
    n implementations selected at runtime through a switch. Unlike
    `dynamic_dispatch` (a bare local existential), boxing the existential in an
    aggregate forces `legalizeExistentialTypeLayout` to float the existential
    field out and recompute the parent layout, and feeds specializeModule a
    witness-table-per-case blowup. Stresses specializeModule +
    legalizeExistentialTypeLayout + the downstream simplifyIR. Scales by breadth
    (number of implementations / switch cases).

    Scaling null: n scales cases, each an O(1) body; ideal specialization cost is O(n).
    """
    s = [_HEADER, _buf()]
    s.append("[anyValueSize(16)]\ninterface IMat { float shade(float x); }\n\n")
    for i in range(n):
        s.append(
            f"struct M{i} : IMat {{ float shade(float x) {{ return x * {i + 1}.0 + {i}.0 + sin(x * {i % 7 + 1}.0); }} }}\n"
        )
    s.append("\nstruct Scene { IMat m; float w; }\n\n")
    s.append("float shadeScene(Scene sc, float x) { return sc.m.shade(x) * sc.w; }\n\n")
    s.append('[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = 0.0;\n    int base = int(tid.x);\n")
    s.append(f"    for (int i = 0; i < {n}; ++i)\n    {{\n        Scene sc;\n")
    s.append(f"        switch ((base + i) % {n})\n        {{\n")
    for i in range(n):
        s.append(f"        case {i}: sc.m = M{i}(); break;\n")
    s.append("        default: sc.m = M0(); break;\n        }\n")
    s.append("        sc.w = float(i);\n        acc += shadeScene(sc, outBuf[0] + float(i));\n    }\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"existential_aggregate.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Complexity ladder: realistic mixed-feature shader scaled simple -> complex.
# --------------------------------------------------------------------------- #

def gen_complexity_ladder(n):
    """A single shader that ramps *several* realistic dimensions together as n
    grows, modelling how a real shader's compile cost behaves going from simple
    to highly complex — as opposed to the single-axis stressors, which isolate
    one pass. Each step adds: a branchy helper (control flow / SSA + phi), a
    generic call (sema + specialization), a small bounded inner loop, resource
    reads, and a dynamic-dispatch site. Helpers are chained in bounded-depth
    groups (call graph depth) so doubling n roughly doubles total work across
    all of front-end, IR opt, and codegen at once. Sweep this to get the
    holistic complexity->compile-time curve and a floor+slope fit.

    Scaling reference (not a null): several axes co-scale, so the sweep's linear line means 'cost tracks code size' — a user-meaningful reference. Standing super-linearity here is expected; the actionable signal is its release-over-release movement.
    """
    s = [_HEADER]
    s.append("RWStructuredBuffer<float> outBuf;\nStructuredBuffer<float> inBuf;\n\n")
    s.append("interface IOp { float apply(float x); }\n")
    s.append("struct OpAdd : IOp { float apply(float x) { return x + 1.0; } }\n")
    s.append("struct OpMul : IOp { float apply(float x) { return x * 1.5 + 0.25; } }\n")
    s.append("struct OpSq  : IOp { float apply(float x) { return x * x - 0.5; } }\n\n")
    s.append("T gpoly<T : IArithmetic>(T a, T b) { return a * a + b * a + a; }\n\n")
    s.append("float dispatch(int id, float x)\n{\n    IOp o;\n    switch (id % 3)\n    {\n")
    s.append("    case 0: o = OpAdd(); break;\n    case 1: o = OpMul(); break;\n")
    s.append("    default: o = OpSq(); break;\n    }\n    return o.apply(x);\n}\n\n")
    # n branchy helpers in bounded-depth call chains.
    group_tops = []
    for i in range(n):
        prev = f"h_{i - 1}(x)" if (i % _GROUP_DEPTH != 0) else "x"
        s.append(f"float h_{i}(float x)\n{{\n    float t = {prev};\n")
        s.append(f"    if (t > {i % 11}.0) t = t * 1.01 + sin(t + {i % 7}.0);\n")
        s.append("    else t = t - cos(t * 0.5) * 0.25;\n")
        s.append(f"    [MaxIters(4)] for (int k = 0; k < (int(t) & 3) + 1; ++k)\n")
        s.append(f"        t = t * 0.999 + gpoly<float>(t, {i % 5}.0);\n")
        s.append("    return t;\n}\n")
        if (i % _GROUP_DEPTH == _GROUP_DEPTH - 1) or i == n - 1:
            group_tops.append(i)
    s.append('\n[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    int idx = int(tid.x);\n    float acc = inBuf[idx];\n")
    for j, top in enumerate(group_tops):
        s.append(f"    acc += h_{top}(acc + float({j}));\n")
        s.append(f"    acc += dispatch(idx + {j}, acc);\n")
    s.append("    acc += float(gpoly<int>(idx, idx + 1));\n")
    s.append("    outBuf[idx] = acc;\n}\n")
    return {"complexity_ladder.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Coverage-gap stressors: passes / paths no other workload exercises.
# --------------------------------------------------------------------------- #

def gen_resource_aggregate(n):
    """n resource-bundle structs (each holding two textures, a sampler and a
    StructuredBuffer) declared at global scope and all read in the entry point.
    Nesting resource handles inside an aggregate forces `legalizeResourceTypes`
    to flatten each struct's resource fields into individually-bound resources
    before a target can consume them — a pass no other workload triggers (every
    other workload's only resource is a bare RWStructuredBuffer). Resources are
    kept live (sampled / indexed into the output) so dead-code elimination can't
    drop them before legalization runs. Scales by breadth = number of bundles,
    i.e. the count of resource fields the pass must legalize; legalizeResourceTypes
    grows super-linearly in n.

    Scaling null: n scales resource-carrying structs, each O(1); ideal legalization cost is O(n) — the measured ~N^1.8 in legalizeResourceTypes is a genuine compiler finding, not a workload property.
    """
    s = [_HEADER]
    s.append("struct ResBundle { Texture2D<float4> albedo; Texture2D<float4> normal; "
             "SamplerState samp; StructuredBuffer<float> coeffs; }\n\n")
    for i in range(n):
        s.append(f"ResBundle bundle_{i};\n")
    s.append("\nRWStructuredBuffer<float> outBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(8,8,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = 0.0;\n    float2 uv = float2(tid.xy) * 0.01;\n")
    for i in range(n):
        s.append(f"    acc += bundle_{i}.albedo.SampleLevel(bundle_{i}.samp, uv, 0).x\n")
        s.append(f"          + bundle_{i}.normal.SampleLevel(bundle_{i}.samp, uv, 0).y\n")
        s.append(f"          + bundle_{i}.coeffs[tid.x % 16];\n")
    s.append("    outBuf[tid.x] = acc;\n}\n")
    return {"resource_aggregate.slang": "".join(s)}


def gen_reflection_layout(n):
    """n constant buffers, each with a structurally rich payload — vectors,
    matrices, an array of a nested `Light` struct, a nested `Material` struct and
    a scalar array. This is the only workload with a large, deeply-typed shader
    *parameter interface* (every other workload's interface is a single
    RWStructuredBuffer), so it is the one stressor for the parameter binding /
    layout-assignment engine and — with `-reflection-json` (see the spec's
    reflection_json flag) — the reflection serializer, the layout/reflection path
    no other workload covers. Scales by breadth = number of
    parameter blocks the layout engine must place and reflect. Note: layout is
    computed during compileInner regardless of the flag (so compileInner is the
    holistic signal); -reflection-json additionally runs the serializer, which is
    cheap today but tracked here for regression coverage.

    Scaling null: n scales parameters; ideal layout cost is O(n).
    """
    s = [_HEADER]
    s.append("struct Light { float3 pos; float3 color; float intensity; float4x4 shadow; }\n")
    s.append("struct Material { float4 base; float metal; float rough; float2 uvScale; float3x3 tangent; }\n\n")
    for i in range(n):
        s.append(f"cbuffer Params{i} : register(b{i})\n{{\n"
                 f"    float4 tint{i};\n    float4x4 xform{i};\n"
                 f"    Light lights{i}[4];\n    Material mat{i};\n    float weights{i}[8];\n}}\n")
    s.append("\nRWStructuredBuffer<float> outBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    for i in range(n):
        s.append(f"    acc += tint{i}.x + xform{i}[0][0] + lights{i}[0].intensity "
                 f"+ mat{i}.metal + weights{i}[0];\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"reflection_layout.slang": "".join(s)}


def gen_control_flow_ssa(n):
    """A single entry point with n stacked control-flow blocks — nested if/else,
    a bounded inner loop with break/continue, and a switch — all mutating a small
    set of carried locals (a, b, c, d). Re-assigning the same locals across many
    branches and loop back-edges is what forces SSA construction to insert phi
    nodes and what the CFG simplifier (constructSSA, inside simplifyIR) must chew
    through. Isolates the SSA/CFG axis that complexity_ladder only touches as one
    of several mixed dimensions; nothing else stresses it alone. Scales by breadth
    = number of control-flow blocks, so basic-block and phi counts grow with n.

    Scaling null: n scales control-flow blocks; ideal SSA construction is near-linear in block count.
    """
    s = [_HEADER]
    s.append("RWStructuredBuffer<float> outBuf;\nStructuredBuffer<float> inBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    int idx = int(tid.x);\n")
    s.append("    float a = inBuf[idx], b = inBuf[idx + 1], c = 0.0, d = 1.0;\n")
    for i in range(n):
        s.append(f"    if ((idx + {i}) % {i % 5 + 2} == 0)\n    {{\n")
        s.append("        a = a * 1.1 + b;\n")
        s.append(f"        [MaxIters(4)] for (int k = 0; k < {i % 4 + 1}; ++k)\n        {{\n")
        s.append("            c += a - b * 0.5;\n")
        s.append(f"            if (c > {i % 9}.0) {{ b = c; break; }}\n")
        s.append("            else { d = d * 0.99 + a; continue; }\n        }\n    }\n")
        s.append(f"    else\n    {{\n        switch ((idx + {i}) % 4)\n        {{\n")
        s.append("        case 0: a -= d; break;\n        case 1: b += c; break;\n")
        s.append("        case 2: c *= 1.01; break;\n        default: d -= a * 0.1;\n        }\n    }\n")
    s.append("    outBuf[idx] = a + b + c + d;\n}\n")
    return {"control_flow_ssa.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Core compiler-stage buckets
# --------------------------------------------------------------------------- #

def gen_parse(n):
    """Large but semantically trivial source: many functions, each a long
    arithmetic expression. Stresses lex/parse with cheap sema.

    Scaling null: n scales statement count; ideal parse cost is O(n).
    """
    s = [_HEADER, _buf()]
    for i in range(n):
        terms = " ".join(
            f"+ {j % 9}.0 * x" if j % 2 else f"- {j % 7}.0 * x" for j in range(40)
        )
        s.append(f"float p_{i}(float x) {{ return x {terms}; }}\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain() { outBuf[0] = p_0(outBuf[0]); }\n")
    return {"parse.slang": "".join(s)}


def gen_sema_generics(n):
    """n distinct generic functions with interface constraints, each instantiated
    at several concrete types. Stresses semantic checking, generic constraint
    satisfaction and instantiation in the front-end.

    Scaling null: n scales instantiation count against a fixed generic set; ideal checking cost is O(n).
    """
    s = [_HEADER, _buf()]
    for i in range(n):
        s.append(
            f"T poly_{i}<T : IArithmetic>(T a, T b) {{ return a * a + b * a + a + b; }}\n"
        )
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n")
    s.append("    float facc = 0.0; int iacc = 0; uint uacc = 0u;\n")
    s.append("    float fx = outBuf[0]; int ix = int(outBuf[0]); uint ux = uint(outBuf[0]);\n")
    for i in range(n):
        s.append(f"    facc += poly_{i}<float>(fx, fx + 1.0);\n")
        s.append(f"    iacc += poly_{i}<int>(ix, ix + 1);\n")
        s.append(f"    uacc += poly_{i}<uint>(ux, ux + 1u);\n")
    s.append("    outBuf[0] = facc + float(iacc) + float(uacc);\n}\n")
    return {"sema_generics.slang": "".join(s)}


def gen_generic_nesting(n):
    """One generic struct instantiated with itself n levels deep: a chain of
    `typealias T_i = Pair<Leaf, T_{i-1}>` where `Pair` is constrained to an
    interface that extends another. Every other generic workload in the suite
    scales BREADTH (many shallow instantiations); this one scales DEPTH, the
    axis on which the front-end's substitution / inheritance-witness work is
    known to multiply per level. The shape arises in real code that composes
    generic "model"/"module" types recursively (e.g. chained ML evaluator
    stacks), where each wrapper layer adds one level of nesting.

    Scaling null: each level adds O(1) declarations, so ideal front-end cost
    is O(n). Measured behavior when this was added (2026-07): substitution
    work grows ~3-4x PER LEVEL (exponential), with the wall-clock knee near
    depth 18 — v2025.14 through tip-of-tree all take ~17-20 s at depth 24.
    The sweep ladder deliberately stays at or below the knee; the finding to
    watch is the top rung's multiple of the linear expectation moving.
    """
    s = [_HEADER]
    s.append("interface IBase {}\n")
    s.append("interface IModel : IBase {}\n")
    s.append("struct Leaf : IModel {}\n\n")
    s.append("struct Pair<First : IModel, Second : IModel> : IModel\n")
    s.append("{\n    First first;\n    Second second;\n}\n\n")
    s.append("typealias T0 = Leaf;\n")
    for i in range(1, n + 1):
        s.append(f"typealias T{i} = Pair<Leaf, T{i-1}>;\n")
    s.append(f"\nT{n} value;\n\n")
    s.append('[shader("compute")]\n[numthreads(1, 1, 1)]\n')
    s.append("void computeMain() {}\n")
    return {"generic_nesting.slang": "".join(s)}


def gen_generic_nesting_eval(n):
    """The generic_nesting chain with a method REQUIRED by the constraint
    interface and called recursively through the witnesses (`first.eval() +
    second.eval()`), so overload resolution and inheritance-witness lookup run
    at every nesting level instead of only type checking the aliases. Same
    depth axis as generic_nesting, much steeper constant: measured ~2.9x per
    level when added (2026-07), vs ~3-4x per level from substitution alone
    but starting an order of magnitude higher at equal depth.

    Scaling null: each level adds O(1) declarations and one call site, so
    ideal front-end cost is O(n). The ladder tops out below generic_nesting's
    because the per-level multiplier bites sooner.
    """
    s = [_HEADER]
    s.append("interface IBase {}\n")
    s.append("interface IModel : IBase { float eval(); }\n")
    s.append("struct Leaf : IModel { float eval() { return 1.0; } }\n\n")
    s.append("struct Pair<First : IModel, Second : IModel> : IModel\n")
    s.append("{\n    First first;\n    Second second;\n")
    s.append("    float eval() { return first.eval() + second.eval(); }\n}\n\n")
    s.append("typealias T0 = Leaf;\n")
    for i in range(1, n + 1):
        s.append(f"typealias T{i} = Pair<Leaf, T{i-1}>;\n")
    s.append("\nRWStructuredBuffer<float> outBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(1, 1, 1)]\n')
    s.append(f"void computeMain() {{ T{n} v; outBuf[0] = v.eval(); }}\n")
    return {"generic_nesting_eval.slang": "".join(s)}


def gen_interface_depth(n):
    """A linear interface inheritance chain n deep (`interface I_k : I_{k-1}`)
    with one struct conforming at the bottom and one generic function
    constrained to the TOP, so conformance checking walks the whole chain.
    Scales the interface-hierarchy depth axis of calcInheritanceInfo — a
    different graph than generic_nesting's type-argument nesting.

    Scaling null: each level adds O(1) declarations, so ideal inheritance-
    info cost is O(n) (or O(n^2) for an all-pairs facet walk); measured
    ~N^3.4 when added (2026-07).
    """
    s = [_HEADER]
    s.append("interface I0 { float get(); }\n")
    for i in range(1, n + 1):
        s.append(f"interface I{i} : I{i-1} {{ }}\n")
    s.append(f"\nstruct S : I{n} {{ float get() {{ return 1.0; }} }}\n\n")
    s.append("float use<T : I0>(T t) { return t.get(); }\n\n")
    s.append("RWStructuredBuffer<float> outBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(1, 1, 1)]\n')
    s.append("void computeMain() { S s; outBuf[0] = use(s); }\n")
    return {"interface_depth.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Type checking: operator overload resolution + implicit conversions
# --------------------------------------------------------------------------- #
# These isolate the front-end type-checker's most quietly expensive work: every
# binary operator and every cross-type assignment runs overload resolution over
# a candidate set and ranks implicit-conversion costs. `parse` deliberately uses
# uniform-`float` arithmetic so each operator matches one overload trivially;
# the workloads below force a *mixed-type* decision at every node instead.

def gen_operator_typecheck(n):
    """`n` functions, each a long arithmetic expression whose operands alternate
    among float/int/uint (typed locals and literals of differing kinds). Every
    `+`/`-`/`*` must resolve the builtin arithmetic operator overload set and
    insert an implicit conversion to the common type — the "checking the types of
    1 and 2 in 1 + 2" cost, multiplied across many nodes. Contrast `parse`, whose
    same-type float expressions skip overload ranking. Module mode -> the signal
    is SemanticChecking, not codegen.

    Scaling null: n scales fixed-length expressions; ideal typecheck cost is O(n).
    """
    s = [_HEADER, _buf()]
    # Each term mixes operand types so the common-type/coercion decision is
    # non-trivial; all conversions are standard widening (int/uint -> float) so
    # the source compiles cleanly across the whole release window.
    terms = [
        "+ 2 * fx", "- ix + 3u", "+ 4.0 * ix", "- ux * 5", "+ fx * 6u",
        "- 7 + ux", "+ ix * 8.0", "- 9u + fx", "+ ux * 10", "- fx * 11",
    ]
    for i in range(n):
        body = " ".join(terms[(i + j) % len(terms)] for j in range(24))
        s.append(
            f"float op_{i}(float fx, int ix, uint ux) {{ return fx {body}; }}\n"
        )
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    s.append("    float fx = outBuf[0]; int ix = int(outBuf[0]); uint ux = uint(outBuf[0]);\n")
    # Cap computeMain call sites at 64: beyond this the entry point itself (not
    # the per-function checking cost we're measuring) becomes the bottleneck.
    for i in range(min(n, 64)):
        s.append(f"    acc += op_{i}(fx, ix, ux);\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"operator_typecheck.slang": "".join(s)}


def gen_implicit_conversion(n):
    """`n` functions, each a cascade of cross-type conversions: scalar widening
    (int/uint -> float), splats, mixed initializer lists (per-element coercion),
    vector compose/truncate, and explicit narrowing. Stresses the coercion /
    conversion-cost engine in semantic checking rather than operator overloading.

    Scaling null: n scales conversion sites against a FIXED type set; ideal cost is O(n).
    """
    s = [_HEADER, _buf()]
    for i in range(n):
        b = [f"float conv_{i}()", "{"]
        b.append(f"    int i = {i % 7}; uint u = {i % 5}u; float f = {i % 9}.0;")
        b.append("    float a = i;")                      # int -> float (widen)
        b.append("    float b = u;")                      # uint -> float (widen)
        b.append("    float2 v2 = f;")                    # scalar -> vector splat
        b.append("    float3 v3 = float3(i, u, f);")      # mixed init: per-elem coerce
        b.append("    float4 v4 = float4(v3, a);")        # vector compose
        b.append("    int2 iv = int2(v2);")               # float2 -> int2 (explicit)
        b.append("    float3 w = v4.xyz;")                # swizzle / truncate
        b.append("    return a + b + v2.x + v3.y + v4.w + float(iv.x) + w.z;")
        b.append("}")
        s.append("\n".join(b) + "\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    # Cap computeMain call sites at 64: beyond this the entry point itself (not
    # the per-function checking cost we're measuring) becomes the bottleneck.
    for i in range(min(n, 64)):
        s.append(f"    acc += conv_{i}();\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"implicit_conversion.slang": "".join(s)}


def gen_overload_resolution(n):
    """A large user-defined overload set (`pick`/`pick2`, scalar + vector + two-arg
    candidates), then `n` call sites with rotating argument types. Every call
    enumerates all candidates and ranks them by conversion cost to choose the best
    match — isolating the candidate-ranking cost that scales with overload-set
    size times call-site count.

    Scaling null: n scales call sites against a FIXED candidate set; ideal resolution cost is O(n).
    """
    s = [_HEADER, _buf()]
    for ty in ("float", "int", "uint", "float2", "float3", "float4"):
        s.append(f"float pick({ty} x) {{ return float(x[0] + x[0]); }}\n"
                 if ty.startswith("float") and ty != "float"
                 else f"float pick({ty} x) {{ return float(x) + 1.0; }}\n")
    # two-argument overloads exercise multi-parameter rank comparison
    for a, bb in (("float", "float"), ("int", "float"), ("float", "int"),
                  ("int", "int"), ("uint", "float"), ("float", "uint")):
        s.append(f"float pick2({a} a, {bb} b) {{ return float(a) + float(b); }}\n")
    s.append("\n")
    args1 = ["1.0", "2", "3u", "float2(1.0)", "float3(1.0)", "float4(1.0)"]
    args2 = [("1.0", "2.0"), ("3", "4.0"), ("5.0", "6"), ("7", "8"),
             ("9u", "10.0"), ("11.0", "12u")]
    for i in range(n):
        a = args1[i % len(args1)]
        p, q = args2[i % len(args2)]
        s.append(f"float call_{i}() {{ return pick({a}) + pick2({p}, {q}); }}\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    # Cap computeMain call sites at 64: beyond this the entry point itself (not
    # the per-function checking cost we're measuring) becomes the bottleneck.
    for i in range(min(n, 64)):
        s.append(f"    acc += call_{i}();\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"overload_resolution.slang": "".join(s)}


def gen_specialization(n):
    """A generic struct over a type parameter, instantiated at n distinct
    wrapper types. Forces specializeModule to clone the generic n ways.

    Scaling null: n scales instantiations of O(1) bodies; ideal specialization cost is O(n).
    """
    s = [_HEADER, _buf()]
    s.append("interface IVal { float get(); }\n\n")
    for i in range(n):
        s.append(f"struct V{i} : IVal {{ float get() {{ return {i}.0 + 1.0; }} }}\n")
    s.append("\nstruct Box<T : IVal> { T v; float compute() { return v.get() * 2.0 + v.get(); } }\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    for i in range(n):
        s.append(f"    {{ Box<V{i}> b; acc += b.compute(); }}\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"specialization.slang": "".join(s)}


def gen_inlining(n):
    """n [ForceInline] functions in bounded-depth groups. The inliner collapses
    each group into its group-top; the entry sums all group-tops, giving the SSA
    simplifier large bodies to chew on. Scales by breadth (bounded nesting).

    Scaling null: n scales call sites with bounded inlining depth; ideal cost is O(n).
    """
    s = [_HEADER, _buf()]
    group_tops = []
    for i in range(n):
        if i % _GROUP_DEPTH == 0:
            s.append(f"[ForceInline] float step_{i}(float x) {{ return x * 1.01 + sin(x); }}\n")
        else:
            s.append(
                f"[ForceInline] float step_{i}(float x) {{ float t = step_{i - 1}(x); return t * 1.01 + cos(t) - sin(x * 0.5); }}\n"
            )
        if (i % _GROUP_DEPTH == _GROUP_DEPTH - 1) or i == n - 1:
            group_tops.append(i)
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float x = outBuf[0]; float acc = 0.0;\n")
    for top in group_tops:
        s.append(f"    acc += step_{top}(x);\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"inlining.slang": "".join(s)}


def gen_codegen(n):
    """A single moderately complex shader. Compiled to multiple targets by the
    harness (same source, varying -target) to isolate generateOutput cost.
    ``n`` scales the amount of straight-line math the backend must emit.

    Scaling null: n scales op count and the emitted output is O(n); ideal codegen cost is O(n).
    """
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float x = outBuf[tid.x];\n    float acc = x;\n")
    for i in range(n):
        s.append(
            f"    acc = acc * 1.0009 + sin(acc + {i}.0) * 0.5 - cos(acc * 0.5) * 0.25 + sqrt(abs(acc) + {i + 1}.0);\n"
        )
    s.append("    outBuf[tid.x] = acc;\n}\n")
    return {"codegen.slang": "".join(s)}


def gen_module_link(n):
    """n importable modules plus a main that imports and uses all of them. The
    harness precompiles each module to .slang-module, then compiles main against
    them, stressing module read + linkIR.

    Scaling null: n scales module count, each O(1); ideal load+link cost is O(n).
    """
    files = {}
    for i in range(n):
        files[f"mod_{i}.slang"] = (
            _HEADER
            + f"module mod_{i};\n\n"
            + f"public float mfun_{i}(float x) {{ return x * {i + 1}.0009 + sin(x + {i}.0); }}\n"
        )
    main = [_HEADER]
    for i in range(n):
        main.append(f"import mod_{i};\n")
    main.append("\n" + _buf())
    main.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    main.append("void computeMain()\n{\n    float acc = outBuf[0];\n")
    for i in range(n):
        main.append(f"    acc = mfun_{i}(acc);\n")
    main.append("    outBuf[0] = acc;\n}\n")
    files["link_main.slang"] = "".join(main)
    return files


# --------------------------------------------------------------------------- #
# API-path workloads (driven by native/api-driver.cpp, not slangc).
# These measure the compilation-API dimension — session setup, module loading,
# per-compile fixed overhead — where application-integration regressions
# amplify (see DESIGN.md "API-path workloads").
# --------------------------------------------------------------------------- #

def gen_api_none(n):
    """The session-create workload needs no sources; the driver only creates
    and destroys sessions (`--iters n` is passed by bench.py)."""
    return {}


def gen_api_kernels(n):
    """n small, mutually independent compute kernels, one file each, the way
    application middleware (e.g. slangpy) generates one kernel per call
    signature. Each kernel is deliberately tiny so per-compile fixed overhead
    (module setup, link, codegen floor) dominates — the dimension where
    small-program regressions amplify."""
    files = {}
    for i in range(n):
        c1 = 1.0 + (i % 89) / 100.0
        c2 = (i % 31) / 10.0
        files[f"kernel_{i:03d}.slang"] = (
            _HEADER
            + f"RWStructuredBuffer<float> buf_{i};\n\n"
            + f"float helper_{i}(float x) {{ return sin(x * {c1}) + x * {c2}; }}\n\n"
            + '[shader("compute")]\n[numthreads(32,1,1)]\n'
            + "void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n"
            + f"    float v = buf_{i}[tid.x];\n"
            + f"    v = helper_{i}(v) + helper_{i}(v * 2.0);\n"
            + f"    buf_{i}[tid.x] = v;\n}}\n"
        )
    return files


def gen_api_module_graph(n):
    """n modules in a layered import DAG (width 8, each module importing up to
    3 from the previous layer) plus a shared interface base and a root that the
    driver loads by name. Unlike module_link's flat one-function modules, each
    module carries an interface conformance, a generic call, and cross-module
    calls — the shape of a real renderer shader library, loaded through the
    API's import-resolution path rather than precompiled .slang-module files."""
    width = 8
    files = {}
    files["gmod_base.slang"] = (
        _HEADER
        + "module gmod_base;\n\n"
        + "public interface IXform { float apply(float x); }\n\n"
        + "public float applyTwice<T : IXform>(T t, float x) { return t.apply(t.apply(x)); }\n"
    )
    for i in range(n):
        layer = i // width
        imports = ["import gmod_base;"]
        calls = []
        if layer > 0:
            prev = [p for p in range(n) if p // width == layer - 1]
            for k in range(min(3, len(prev))):
                p = prev[(i + k) % len(prev)]
                imports.append(f"import gmod_{p};")
                # Call the imported module's non-recursive leaf, NOT its chain:
                # chains calling chains multiplies inlined code by fan-in^depth
                # and the compile explodes (observed as OOM-kill at n=150).
                # Leaf calls keep codegen linear in n while the import DAG —
                # the load/check cost this workload exists to measure — stays
                # just as deep.
                calls.append(f"    r += leaf_{p}(r * 0.99{k});\n")
        body = (
            _HEADER
            + f"module gmod_{i};\n"
            + "\n".join(imports) + "\n\n"
            + f"public struct Xf_{i} : IXform\n{{\n"
            + f"    public float apply(float x) {{ return x * 1.00{i % 97} + 0.0{i % 13}; }}\n}}\n\n"
            + f"public float leaf_{i}(float x) {{ return sin(x * 1.0{i % 7}) + x * 0.5{i % 11}; }}\n\n"
            + f"public float chain_{i}(float x)\n{{\n"
            + f"    Xf_{i} xf;\n"
            + f"    float r = applyTwice(xf, x);\n"
            + "".join(calls)
            + "    return r;\n}\n"
        )
        files[f"gmod_{i}.slang"] = body
    top = [i for i in range(n) if i // width == (n - 1) // width]
    main = [_HEADER, "module graph_main;\n"]
    for i in top:
        main.append(f"import gmod_{i};\n")
    main.append("\n" + _buf())
    main.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    main.append("void computeMain()\n{\n    float acc = outBuf[0];\n")
    for i in top:
        main.append(f"    acc = chain_{i}(acc);\n")
    main.append("    outBuf[0] = acc;\n}\n")
    files["graph_main.slang"] = "".join(main)
    return files


def gen_api_reflect_kernels(n):
    """n kernels with deliberately parameter-rich signatures (nested constant
    buffers, arrays, textures, samplers) so that walking each compiled
    program's layout — the reflection query pattern every API client uses to
    build binding tables — has realistic work per program. Used with the
    driver's --reflect option, which walks the layout after each compile."""
    files = {}
    for i in range(n):
        files[f"kernel_{i:03d}.slang"] = (
            _HEADER
            + f"struct Inner_{i}\n{{\n    float4 a;\n    float3 b;\n    int2 c[4];\n}}\n\n"
            + f"struct Params_{i}\n{{\n    Inner_{i} inner[3];\n    float4x4 xf;\n"
            + f"    uint flags;\n    float blend[{2 + i % 5}];\n}}\n\n"
            + f"ConstantBuffer<Params_{i}> cb_{i};\n"
            + f"StructuredBuffer<float4> inBuf_{i};\n"
            + f"RWStructuredBuffer<float4> outBuf_{i};\n"
            + f"Texture2D tex_{i};\nSamplerState samp_{i};\n\n"
            + '[shader("compute")]\n[numthreads(8,8,1)]\n'
            + "void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n"
            + f"    float4 v = inBuf_{i}[tid.x];\n"
            + f"    v += tex_{i}.SampleLevel(samp_{i}, v.xy, 0);\n"
            + f"    v *= mul(cb_{i}.xf, v);\n"
            + f"    v.x += cb_{i}.inner[tid.x % 3].a.x + cb_{i}.blend[0];\n"
            + f"    outBuf_{i}[tid.x] = v;\n}}\n"
        )
    return files


def gen_api_specialize(n):
    """One module with an interface, n conforming impl structs, and a generic
    computeMain<T : IOp>. The driver's specialize mode compiles one variant
    per impl through IEntryPoint::specialize — the application pattern where
    one kernel is stamped out per material/config type, stressing
    specialization + link cost per variant."""
    src = [_HEADER, "module spec_root;\n\n"]
    src.append("public interface IOp\n{\n    static float eval(float x);\n}\n\n")
    for i in range(n):
        c1 = 1.0 + (i % 89) / 100.0
        c2 = (i % 31) / 10.0
        src.append(
            f"public struct Impl_{i} : IOp\n{{\n"
            f"    public static float eval(float x) {{ return sin(x * {c1}) + x * {c2}; }}\n}}\n\n"
        )
    src.append(_buf())
    src.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    src.append("void computeMain<T : IOp>()\n{\n    outBuf[0] = T.eval(outBuf[0]);\n}\n")
    return {"spec_root.slang": "".join(src)}


# --------------------------------------------------------------------------- #
# rt_renderer: a generated renderer-shaped corpus (DESIGN.md Phase 2).
#
# Replicates the shape of a real application's shader library. The internal
# benchmark whose regression sensitivity motivated the api workloads compiles
# ~10-25 programs per test, each importing a ~160-module / ~28k-line renderer
# library (utility/scene/material layers, interface-driven materials), which
# makes every program a few-hundred-ms compile: few×HEAVY, where
# api_many_kernels is many×tiny. Those figures describe the replicated
# ORIGINAL; this generator produces the same shape at ~100 modules with the
# default n=24 materials (see the constants below). Being generated, the
# corpus is deterministic
# (same n -> identical bytes): no external checkout, no license surface, no
# pinning, and no corpus-drift resyncs.
# --------------------------------------------------------------------------- #

# Library shape constants: ~48 utility + 24 scene + n material modules + base +
# entry-point roots. With the default n=24 that is ~100 modules and around the
# internal library's line count once each module's body is realistic.
_RT_UTILS = 48
_RT_SCENE = 24



def _rt_pick_distinct(base, stride, count, modulo):
    """Deterministically pick `count` DISTINCT indices in [0, modulo): walk
    base + k*stride and skip collisions. Callers import each picked module and
    index the result positionally, so distinctness is a hard requirement, not
    an accident of the current stride/modulo choice.

    Precondition: count <= modulo // gcd(stride, modulo) — the walk only ever
    visits that many distinct residues, so a triple outside the bound could
    never terminate. Asserted so a bad future constant fails loudly instead of
    hanging corpus generation."""
    import math
    cycle_len = modulo // math.gcd(stride, modulo)
    assert count <= cycle_len, (
        f"_rt_pick_distinct: cannot pick {count} distinct values from a walk "
        f"of cycle length {cycle_len} (stride={stride}, modulo={modulo})")
    picks = []
    k = 0
    while len(picks) < count:
        c = (base + k * stride) % modulo
        if c not in picks:
            picks.append(c)
        k += 1
    return picks


def _rt_util_module(i):
    """One utility-layer module: original math/sampling helpers with a couple
    of imports from earlier utility modules so the layer forms a DAG."""
    imports = []
    calls = []
    if i > 0:
        a = (i * 7 + 1) % i
        imports.append(f"import rutil_{a};\n")
        calls.append(f"    r += util_hash_{a}(r.x + {i}.0) * 0.125;\n")
    if i > 1:
        b = (i * 13 + 5) % i
        if f"import rutil_{b};\n" not in imports:
            imports.append(f"import rutil_{b};\n")
            calls.append(f"    r = util_warp_{b}(r * 0.99{i % 10});\n")
    c1, c2, c3 = 1.0 + (i % 89) / 100.0, (i % 31) / 10.0, 1.0 + (i % 7) / 8.0
    return (
        _HEADER
        + f"module rutil_{i};\nimport rutil_base;\n" + "".join(imports) + "\n"
        + f"public float3 util_hash_{i}(float x)\n{{\n"
        + f"    float3 v = float3(x * {c1}, x + {c2}, x - {c3});\n"
        + "    v = frac(sin(v * 127.1) * 43758.5453);\n"
        + "    return v;\n}\n\n"
        + f"public float3 util_warp_{i}(float3 s)\n{{\n"
        + f"    float a = s.x * {c1} + s.y * {c2};\n"
        + "    float b = sqrt(max(1.0 - a * a, 0.0));\n"
        + f"    float3 r = float3(b * cos(s.z * {c3}), b * sin(s.z * {c3}), a);\n"
        + "".join(calls)
        + "    return normalize(r + 1e-5);\n}\n\n"
        + f"public float util_lum_{i}(float3 c)\n{{\n"
        + f"    return dot(c, float3(0.2126, 0.7152, 0.0722)) * {c3};\n}}\n"
    )


def _rt_scene_module(i, n_utils):
    """One scene-layer module (lights/camera/intersection helpers) importing a
    handful of utility modules and, above layer 0, earlier scene modules."""
    us = _rt_pick_distinct(i * 5, 11, 3, n_utils)
    imports = "".join(f"import rutil_{u};\n" for u in us)
    # scene_light_{i} calls scene_light_{i-1}: a LINEAR chain (fan-in 1), so
    # inlined size grows O(_RT_SCENE) per call site — unlike the fan-in^depth
    # chain-of-chains that OOM'd gen_api_module_graph's first version (its
    # leaf-only rule targets multiplicative growth, which a 1-ary chain has
    # none of).
    prev = f"import rscene_{i - 1};\n" if i > 0 else ""
    prev_call = f"    l += scene_light_{i - 1}(p * 0.97, n);\n" if i > 0 else ""
    c = 1.0 + (i % 13) / 16.0
    return (
        _HEADER
        + f"module rscene_{i};\nimport rutil_base;\n" + imports + prev + "\n"
        + f"public struct Light_{i}\n{{\n"
        + "    public float3 position;\n    public float3 intensity;\n"
        + "    public float radius;\n}\n\n"
        + f"public float3 scene_light_{i}(float3 p, float3 n)\n{{\n"
        + f"    Light_{i} light;\n"
        + f"    light.position = util_hash_{us[0]}(p.x) * 10.0;\n"
        + f"    light.intensity = float3({c}, {c} * 0.9, {c} * 0.8);\n"
        + "    light.radius = 0.5;\n"
        + "    float3 toL = light.position - p;\n"
        + "    float d2 = max(dot(toL, toL), 1e-4);\n"
        + "    float3 l = light.intensity * max(dot(n, normalize(toL)), 0.0) / d2;\n"
        + prev_call
        + "    return l;\n}\n\n"
        + f"public float scene_shadow_{i}(float3 p)\n{{\n"
        + f"    return saturate(util_lum_{us[1]}(util_warp_{us[2]}(p)));\n}}\n"
    )


def _rt_material_module(i, n_utils, n_scene):
    """One material module: a BSDF and a material conforming to the shared
    interfaces, with texture/sampler/parameter state and eval/sample methods
    that lean on the utility and scene layers."""
    us = _rt_pick_distinct(i * 17, 7, 4, n_utils)
    sc = (i * 3) % n_scene
    imports = "".join(f"import rutil_{u};\n" for u in us) + f"import rscene_{sc};\n"
    r = 0.1 + (i % 9) / 10.0
    return (
        _HEADER
        + f"module rmat_{i};\nimport rutil_base;\nimport rmat_base;\n" + imports + "\n"
        + f"public struct BSDF_{i} : IBSDF\n{{\n"
        + "    public float3 albedo;\n    public float roughness;\n\n"
        + "    public float3 eval(float3 wi, float3 wo, float3 n)\n    {\n"
        + "        float3 h = normalize(wi + wo);\n"
        + f"        float d = pow(max(dot(n, h), 0.0), 1.0 / max(roughness * {r}, 1e-3));\n"
        + f"        float3 f = albedo + (1.0 - albedo) * pow(1.0 - max(dot(wi, h), 0.0), 5.0);\n"
        + "        return f * d * max(dot(n, wo), 0.0);\n    }\n\n"
        + "    public float3 sample(float3 wi, float3 n, float2 u)\n    {\n"
        + f"        return util_warp_{us[0]}(float3(u, roughness));\n    }}\n\n"
        + "    public float pdf(float3 wi, float3 wo, float3 n)\n    {\n"
        + f"        return max(util_lum_{us[1]}(eval(wi, wo, n)), 1e-4);\n    }}\n}}\n\n"
        + f"public struct Material_{i} : IMaterial\n{{\n"
        + f"    public Texture2D albedoMap;\n    public SamplerState samp;\n"
        + f"    public float4 tint;\n\n"
        + "    public float3 shade(float3 p, float3 n, float3 wi, float3 wo, float2 uv)\n"
        + "    {\n"
        + f"        BSDF_{i} bsdf;\n"
        + "        bsdf.albedo = albedoMap.SampleLevel(samp, uv, 0).rgb * tint.rgb;\n"
        + f"        bsdf.roughness = tint.a * {r};\n"
        + f"        float3 li = scene_light_{sc}(p, n) * scene_shadow_{sc}(p);\n"
        + "        return bsdf.eval(wi, wo, n) * li;\n    }\n\n"
        + "    public static float3 evalStatic(float3 p, float3 n, float2 uv)\n    {\n"
        + f"        BSDF_{i} bsdf;\n"
        + f"        bsdf.albedo = util_hash_{us[2]}(uv.x);\n"
        + f"        bsdf.roughness = {r};\n"
        + f"        float3 wi = util_warp_{us[3]}(float3(uv, 0.5));\n"
        + "        return bsdf.eval(wi, n, n) + scene_light_" + str(sc) + "(p, n);\n    }\n}\n"
    )


def gen_rt_renderer(n):
    """A renderer-shaped generated corpus: utility + scene + material layers
    behind IMaterial/IBSDF interfaces (n = material count), a raygen/
    closesthit/miss entry-point root importing the whole library, and a
    generic compute root for per-material specialization. Programs here are
    few×HEAVY — each imports the full library — complementing
    api_many_kernels' many×tiny per-compile-overhead probes."""
    files = {}
    files["rutil_base.slang"] = (
        _HEADER + "module rutil_base;\n\n"
        + "public float3 frac3(float3 v) { return frac(v); }\n"
        + "public static const float kPi = 3.14159265358979;\n"
    )
    files["rmat_base.slang"] = (
        _HEADER + "module rmat_base;\n\n"
        + "public interface IBSDF\n{\n"
        + "    float3 eval(float3 wi, float3 wo, float3 n);\n"
        + "    float3 sample(float3 wi, float3 n, float2 u);\n"
        + "    float pdf(float3 wi, float3 wo, float3 n);\n}\n\n"
        + "public interface IMaterial\n{\n"
        + "    static float3 evalStatic(float3 p, float3 n, float2 uv);\n}\n"
    )
    for i in range(_RT_UTILS):
        files[f"rutil_{i}.slang"] = _rt_util_module(i)
    for i in range(_RT_SCENE):
        files[f"rscene_{i}.slang"] = _rt_scene_module(i, _RT_UTILS)
    for i in range(n):
        files[f"rmat_{i}.slang"] = _rt_material_module(i, _RT_UTILS, _RT_SCENE)

    lib = [_HEADER, "module rlib;\n"]
    for i in range(_RT_UTILS):
        lib.append(f"__exported import rutil_{i};\n")
    for i in range(_RT_SCENE):
        lib.append(f"__exported import rscene_{i};\n")
    lib.append("__exported import rmat_base;\n")
    for i in range(n):
        lib.append(f"__exported import rmat_{i};\n")
    files["rlib.slang"] = "".join(lib)

    # RT entry-point root: raygen + closesthit + miss over the whole library,
    # composed into one program by the driver's rt-composite mode.
    rt = [_HEADER, "module rt_kernels;\nimport rlib;\n\n"]
    rt.append("RaytracingAccelerationStructure gScene;\n")
    rt.append("RWTexture2D<float4> gOutput;\n\n")
    rt.append("struct RayPayload\n{\n    float3 color;\n    uint depth;\n}\n\n")
    w = 1.0 / max(n, 1)
    shade = "".join(
        f"    c += Material_{i}.evalStatic(p, n, uv) * {w:.4f};\n" for i in range(n)
    )
    rt.append(
        '[shader("raygen")]\nvoid rayGenMain()\n{\n'
        "    uint2 idx = DispatchRaysIndex().xy;\n"
        "    RayDesc ray;\n"
        "    ray.Origin = float3(idx.x * 0.001, idx.y * 0.001, -1.0);\n"
        "    ray.Direction = float3(0, 0, 1);\n"
        "    ray.TMin = 0.0;\n    ray.TMax = 1e30;\n"
        "    RayPayload payload = { float3(0, 0, 0), 0 };\n"
        "    TraceRay(gScene, RAY_FLAG_NONE, 0xff, 0, 0, 0, ray, payload);\n"
        "    gOutput[idx] = float4(payload.color, 1.0);\n}\n\n"
    )
    rt.append(
        '[shader("miss")]\nvoid missMain(inout RayPayload payload)\n{\n'
        "    payload.color = float3(0.1, 0.2, 0.4);\n}\n\n"
    )
    rt.append(
        '[shader("closesthit")]\nvoid closestHitMain(\n'
        "    inout RayPayload payload,\n"
        "    in BuiltInTriangleIntersectionAttributes attribs)\n{\n"
        "    float3 p = WorldRayOrigin() + WorldRayDirection() * RayTCurrent();\n"
        "    float3 n = float3(0, 1, 0);\n"
        "    float2 uv = attribs.barycentrics;\n"
        "    float3 c = float3(0, 0, 0);\n"
        + shade
        + "    payload.color = c;\n    payload.depth += 1;\n}\n"
    )
    files["rt_kernels.slang"] = "".join(rt)

    # Generic compute root: one kernel specialized per material by the
    # driver's specialize mode (--impl-prefix Material_).
    files["rt_compute.slang"] = (
        _HEADER + "module rt_compute;\nimport rlib;\n\n" + _buf()
        + '[shader("compute")]\n[numthreads(8,8,1)]\n'
        + "void computeMain<T : IMaterial>(uint3 tid : SV_DispatchThreadID)\n{\n"
        + "    float2 uv = float2(tid.xy) * 0.001;\n"
        + "    float3 c = T.evalStatic(float3(uv, 0.0), float3(0, 1, 0), uv);\n"
        + "    outBuf[tid.x] = c.x + c.y + c.z;\n}\n"
    )
    return files

def _read_corpus(name):
    d = os.path.join(_CORPUS, name)
    if not os.path.isdir(d):
        raise FileNotFoundError(
            f"corpus '{name}' missing at {d}; copy .slang files there before running"
        )
    out = {}
    for fn in sorted(os.listdir(d)):
        if fn.endswith(".slang"):
            with open(os.path.join(d, fn), "rb") as fh:
                out[fn] = fh.read().decode("utf-8", "replace")
    if not out:
        raise FileNotFoundError(f"no .slang files in corpus '{name}' ({d})")
    return out


def gen_mdl_dxr(n):
    """Real MDL/DXR path-tracing shaders (shader-slang/MDL-SDK). `n` is ignored
    (fixed corpus). Compiled monolithically from hit.slang, which imports the
    rest. This is a holistic real-world compile-time number."""
    return _read_corpus("mdl")
