"""Deterministic, size-scalable Slang workload generators for the compile-time
perf suite.

Each generator is a function ``gen(n) -> dict[str, str]`` mapping a filename to
Slang source. Most workloads are a single file; the module-link workload emits
several. Generators must be deterministic (same ``n`` -> identical bytes) so a
release sweep compares like with like.

Conventions:
- Every compilable workload exposes a ``[shader("compute")]`` entry named
  ``computeMain`` so ``slangc`` auto-discovers it; results are written to a
  ``RWStructuredBuffer`` so nothing is dead-code-eliminated.
"""

import os

_HEADER = "// AUTO-GENERATED by perf-suite/workloads.py — do not edit by hand.\n"
_CORPUS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "corpus")


def _buf():
    """Standard output-buffer declaration used by every compilable workload.

    All workload generators write results into `outBuf` so that nothing is
    dead-code-eliminated before the targeted compiler stage runs.
    """
    return "RWStructuredBuffer<float> outBuf;\n\n"


# --------------------------------------------------------------------------- #
# Per-compile floor
# --------------------------------------------------------------------------- #

def gen_minimal(n):
    """Near-empty shader: isolates the fixed per-compile floor — core-module
    deserialization (readSerializedModuleIR/AST, loadBuiltinModule) plus linkIR
    of the user module against the core module — with negligible user-code work.

    This is the cleanest detector for "the standard library got heavier"
    regressions: when the core module grows, every compile pays here regardless
    of which language features it uses (the class of regression introduced by the
    auto-diff overhaul in PR #9808, where an empty shader's linkIR rose ~27x)."""
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID) { outBuf[tid.x] = float(tid.x); }\n")
    return {"minimal.slang": "".join(s)}


def gen_ir_builder(n):
    """One enormous straight-line function: `n` trivial integer SSA ops, almost
    no semantic work. Stresses IR instruction construction / dedup / hash-cons
    and the SSA simplifier (the shared IRBuilder layer PR #9808 touched)."""
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    int acc = int(tid.x);\n")
    for i in range(n):
        op = "*" if i % 3 == 0 else ("+" if i % 3 == 1 else "^")
        s.append(f"    acc = acc {op} {i % 13 + 1};\n")
    s.append("    outBuf[0] = float(acc);\n}\n")
    return {"ir_builder.slang": "".join(s)}


def gen_serialize(n):
    """A large module of `n` public functions, compiled to a .slang-module.
    Stresses IR/AST serialization (writeSerializedModule*) — the write side of
    the cost whose read side (readSerializedModule*) the `minimal` floor test
    and module loading exercise."""
    s = [_HEADER]
    for i in range(n):
        s.append(
            f"public float sfn_{i}(float x, float y) {{ return x * {i % 7 + 1}.0 + y * {i % 5 + 1}.0 + sin(x + {i}.0); }}\n"
        )
    return {"serialize.slang": "".join(s)}


def gen_conformance(n):
    """`n` structs each conforming to a shared interface. Stresses interface
    conformance checking / witness synthesis in the front end (compiled to a
    .slang-module so the signal is sema, not codegen)."""
    s = [_HEADER]
    s.append("interface IFace { float f(float x); int g(); }\n\n")
    for i in range(n):
        s.append(
            f"struct C{i} : IFace {{ float f(float x) {{ return x * {i % 9 + 1}.0 + {i}.0; }} "
            f"int g() {{ return {i}; }} }}\n"
        )
    return {"conformance.slang": "".join(s)}


def gen_loop_unroll(n):
    """A force-unrolled loop of `n` iterations. Stresses loop unrolling
    (unrollLoopsInModule) and the downstream SSA simplify on the unrolled body."""
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = outBuf[tid.x];\n")
    s.append(f"    [ForceUnroll] for (int i = 0; i < {n}; ++i)\n")
    s.append("        acc = acc * 1.0009 + sin(acc + float(i)) * 0.5 - cos(acc * 0.5);\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"loop_unroll.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Suspected-regression features
# --------------------------------------------------------------------------- #

# Call depth within a group. Work scales by *breadth* (number of groups), while
# nesting stays bounded so we don't hit the compiler's type-nesting recursion cap
# (~32 levels in practice). 8 gives ~4× margin and is empirically safe up to
# n=1280 (the largest sweep size used).
_GROUP_DEPTH = 8


def gen_autodiff(n):
    """n differentiable functions arranged in bounded-depth groups, each group
    differentiated in both forward and reverse mode, plus a differentiable
    generic. Stresses the autodiff IR transform (inside linkAndOptimizeIR) and
    the front-end checking of [Differentiable]. Scales by breadth."""
    s = [_HEADER, _buf()]
    s.append("[Differentiable]\n")
    s.append("float leaf(float x) { return x * x + sin(x) * cos(x); }\n\n")
    group_tops = []
    for i in range(n):
        prev = "leaf" if (i % _GROUP_DEPTH == 0) else f"chain_{i - 1}"
        s.append("[Differentiable]\n")
        s.append(
            f"float chain_{i}(float x) {{ return {prev}(x) * 1.0009 + sin(x) * 0.5 - cos(x) * 0.25; }}\n"
        )
        if (i % _GROUP_DEPTH == _GROUP_DEPTH - 1) or i == n - 1:
            group_tops.append(i)
    s.append("\n")
    # A differentiable generic instantiated for float.
    s.append("[Differentiable]\n")
    s.append("T poly<T : IDifferentiable & IFloat>(T x) { return x * x * x + x; }\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float x = outBuf[tid.x];\n    float acc = 0.0;\n")
    for top in group_tops:
        s.append("    { var dp = diffPair(x, 1.0);\n")
        s.append(f"      bwd_diff(chain_{top})(dp, 1.0); acc += dp.d;\n")
        s.append(f"      acc += fwd_diff(chain_{top})(diffPair(x, 1.0)).d; }}\n")
    s.append("    acc += fwd_diff(poly<float>)(diffPair(x, 1.0)).d;\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"autodiff.slang": "".join(s)}


def gen_dynamic_dispatch(n):
    """One interface, n implementations, called through an existential whose
    concrete type is chosen at runtime (defeats static specialization, forcing
    witness-table dynamic dispatch). Stresses dispatch lowering / specializeModule."""
    s = [_HEADER, _buf()]
    s.append("[anyValueSize(16)]\ninterface IShape { float eval(float x); }\n\n")
    for i in range(n):
        s.append(
            f"struct Shape{i} : IShape {{ float eval(float x) {{ return x * {i + 1}.0 + {i}.0 + sin(x * {i + 1}.0); }} }}\n"
        )
    s.append("\nfloat dispatch(int id, float x)\n{\n    IShape s;\n    switch (id)\n    {\n")
    for i in range(n):
        s.append(f"    case {i}: s = Shape{i}(); break;\n")
    s.append("    default: s = Shape0(); break;\n    }\n    return s.eval(x);\n}\n\n")
    s.append("float run(IShape s, float x) { return s.eval(x); }\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = 0.0;\n")
    s.append("    int base = int(tid.x);\n")
    s.append(f"    for (int i = 0; i < {n}; ++i)\n")
    s.append("        acc += dispatch((base + i) % " + str(n) + ", outBuf[0] + float(i));\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"dynamic_dispatch.slang": "".join(s)}


def gen_diagnostics_clean(n):
    """N functions with distinct compile-time constants, no errors."""
    s = [_HEADER, _buf()]
    for i in range(n):
        s.append(f"static const float k_{i} = {i % 7}.0;\n")
        s.append(f"float ok_{i}(float x) {{ return x + k_{i} * {i % 5 + 1}.0; }}\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    s.append(f"    for (int i = 0; i < {n}; ++i) acc += ok_0(float(i));\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"diagnostics_clean.slang": "".join(s)}


def gen_existential_aggregate(n):
    """An interface-typed *field* inside a struct (`Scene { IMat m; ... }`), with
    n implementations selected at runtime through a switch. Unlike
    `dynamic_dispatch` (a bare local existential), boxing the existential in an
    aggregate forces `legalizeExistentialTypeLayout` to float the existential
    field out and recompute the parent layout, and feeds specializeModule a
    witness-table-per-case blowup. Stresses specializeModule +
    legalizeExistentialTypeLayout + the downstream simplifyIR. Scales by breadth
    (number of implementations / switch cases)."""
    s = [_HEADER, _buf()]
    s.append("[anyValueSize(16)]\ninterface IMat { float shade(float x); }\n\n")
    for i in range(n):
        s.append(
            f"struct M{i} : IMat {{ float shade(float x) {{ return x * {i + 1}.0 + {i}.0 + sin(x * {i % 7 + 1}.0); }} }}\n"
        )
    s.append("\nstruct Scene { IMat m; float w; }\n\n")
    s.append("float shadeScene(Scene sc, float x) { return sc.m.shade(x) * sc.w; }\n\n")
    s.append('[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = 0.0;\n    int base = int(tid.x);\n")
    s.append(f"    for (int i = 0; i < {n}; ++i)\n    {{\n        Scene sc;\n")
    s.append(f"        switch ((base + i) % {n})\n        {{\n")
    for i in range(n):
        s.append(f"        case {i}: sc.m = M{i}(); break;\n")
    s.append("        default: sc.m = M0(); break;\n        }\n")
    s.append("        sc.w = float(i);\n        acc += shadeScene(sc, outBuf[0] + float(i));\n    }\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"existential_aggregate.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Complexity ladder: realistic mixed-feature shader scaled simple -> complex.
# --------------------------------------------------------------------------- #

def gen_complexity_ladder(n):
    """A single shader that ramps *several* realistic dimensions together as n
    grows, modelling how a real shader's compile cost behaves going from simple
    to highly complex — as opposed to the single-axis stressors, which isolate
    one pass. Each step adds: a branchy helper (control flow / SSA + phi), a
    generic call (sema + specialization), a small bounded inner loop, resource
    reads, and a dynamic-dispatch site. Helpers are chained in bounded-depth
    groups (call graph depth) so doubling n roughly doubles total work across
    all of front-end, IR opt, and codegen at once. Sweep this to get the
    holistic complexity->compile-time curve and a floor+slope fit."""
    s = [_HEADER]
    s.append("RWStructuredBuffer<float> outBuf;\nStructuredBuffer<float> inBuf;\n\n")
    s.append("interface IOp { float apply(float x); }\n")
    s.append("struct OpAdd : IOp { float apply(float x) { return x + 1.0; } }\n")
    s.append("struct OpMul : IOp { float apply(float x) { return x * 1.5 + 0.25; } }\n")
    s.append("struct OpSq  : IOp { float apply(float x) { return x * x - 0.5; } }\n\n")
    s.append("T gpoly<T : IArithmetic>(T a, T b) { return a * a + b * a + a; }\n\n")
    s.append("float dispatch(int id, float x)\n{\n    IOp o;\n    switch (id % 3)\n    {\n")
    s.append("    case 0: o = OpAdd(); break;\n    case 1: o = OpMul(); break;\n")
    s.append("    default: o = OpSq(); break;\n    }\n    return o.apply(x);\n}\n\n")
    # n branchy helpers in bounded-depth call chains.
    group_tops = []
    for i in range(n):
        prev = f"h_{i - 1}(x)" if (i % _GROUP_DEPTH != 0) else "x"
        s.append(f"float h_{i}(float x)\n{{\n    float t = {prev};\n")
        s.append(f"    if (t > {i % 11}.0) t = t * 1.01 + sin(t + {i % 7}.0);\n")
        s.append("    else t = t - cos(t * 0.5) * 0.25;\n")
        s.append(f"    [MaxIters(4)] for (int k = 0; k < (int(t) & 3) + 1; ++k)\n")
        s.append(f"        t = t * 0.999 + gpoly<float>(t, {i % 5}.0);\n")
        s.append("    return t;\n}\n")
        if (i % _GROUP_DEPTH == _GROUP_DEPTH - 1) or i == n - 1:
            group_tops.append(i)
    s.append('\n[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    int idx = int(tid.x);\n    float acc = inBuf[idx];\n")
    for j, top in enumerate(group_tops):
        s.append(f"    acc += h_{top}(acc + float({j}));\n")
        s.append(f"    acc += dispatch(idx + {j}, acc);\n")
    s.append("    acc += float(gpoly<int>(idx, idx + 1));\n")
    s.append("    outBuf[idx] = acc;\n}\n")
    return {"complexity_ladder.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Coverage-gap stressors: passes / paths no other workload exercises.
# --------------------------------------------------------------------------- #

def gen_resource_aggregate(n):
    """n resource-bundle structs (each holding two textures, a sampler and a
    StructuredBuffer) declared at global scope and all read in the entry point.
    Nesting resource handles inside an aggregate forces `legalizeResourceTypes`
    to flatten each struct's resource fields into individually-bound resources
    before a target can consume them — a pass no other workload triggers (every
    other workload's only resource is a bare RWStructuredBuffer). Resources are
    kept live (sampled / indexed into the output) so dead-code elimination can't
    drop them before legalization runs. Scales by breadth = number of bundles,
    i.e. the count of resource fields the pass must legalize; legalizeResourceTypes
    grows super-linearly in n."""
    s = [_HEADER]
    s.append("struct ResBundle { Texture2D<float4> albedo; Texture2D<float4> normal; "
             "SamplerState samp; StructuredBuffer<float> coeffs; }\n\n")
    for i in range(n):
        s.append(f"ResBundle bundle_{i};\n")
    s.append("\nRWStructuredBuffer<float> outBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(8,8,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float acc = 0.0;\n    float2 uv = float2(tid.xy) * 0.01;\n")
    for i in range(n):
        s.append(f"    acc += bundle_{i}.albedo.SampleLevel(bundle_{i}.samp, uv, 0).x\n")
        s.append(f"          + bundle_{i}.normal.SampleLevel(bundle_{i}.samp, uv, 0).y\n")
        s.append(f"          + bundle_{i}.coeffs[tid.x % 16];\n")
    s.append("    outBuf[tid.x] = acc;\n}\n")
    return {"resource_aggregate.slang": "".join(s)}


def gen_reflection_layout(n):
    """n constant buffers, each with a structurally rich payload — vectors,
    matrices, an array of a nested `Light` struct, a nested `Material` struct and
    a scalar array. This is the only workload with a large, deeply-typed shader
    *parameter interface* (every other workload's interface is a single
    RWStructuredBuffer), so it is the one stressor for the parameter binding /
    layout-assignment engine and — with `-reflection-json` (see the spec's
    reflection_json flag) — the reflection serializer, the layout/reflection path
    no other workload covers. Scales by breadth = number of
    parameter blocks the layout engine must place and reflect. Note: layout is
    computed during compileInner regardless of the flag (so compileInner is the
    holistic signal); -reflection-json additionally runs the serializer, which is
    cheap today but tracked here for regression coverage."""
    s = [_HEADER]
    s.append("struct Light { float3 pos; float3 color; float intensity; float4x4 shadow; }\n")
    s.append("struct Material { float4 base; float metal; float rough; float2 uvScale; float3x3 tangent; }\n\n")
    for i in range(n):
        s.append(f"cbuffer Params{i} : register(b{i})\n{{\n"
                 f"    float4 tint{i};\n    float4x4 xform{i};\n"
                 f"    Light lights{i}[4];\n    Material mat{i};\n    float weights{i}[8];\n}}\n")
    s.append("\nRWStructuredBuffer<float> outBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    for i in range(n):
        s.append(f"    acc += tint{i}.x + xform{i}[0][0] + lights{i}[0].intensity "
                 f"+ mat{i}.metal + weights{i}[0];\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"reflection_layout.slang": "".join(s)}


def gen_control_flow_ssa(n):
    """A single entry point with n stacked control-flow blocks — nested if/else,
    a bounded inner loop with break/continue, and a switch — all mutating a small
    set of carried locals (a, b, c, d). Re-assigning the same locals across many
    branches and loop back-edges is what forces SSA construction to insert phi
    nodes and what the CFG simplifier (constructSSA, inside simplifyIR) must chew
    through. Isolates the SSA/CFG axis that complexity_ladder only touches as one
    of several mixed dimensions; nothing else stresses it alone. Scales by breadth
    = number of control-flow blocks, so basic-block and phi counts grow with n."""
    s = [_HEADER]
    s.append("RWStructuredBuffer<float> outBuf;\nStructuredBuffer<float> inBuf;\n\n")
    s.append('[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    int idx = int(tid.x);\n")
    s.append("    float a = inBuf[idx], b = inBuf[idx + 1], c = 0.0, d = 1.0;\n")
    for i in range(n):
        s.append(f"    if ((idx + {i}) % {i % 5 + 2} == 0)\n    {{\n")
        s.append("        a = a * 1.1 + b;\n")
        s.append(f"        [MaxIters(4)] for (int k = 0; k < {i % 4 + 1}; ++k)\n        {{\n")
        s.append("            c += a - b * 0.5;\n")
        s.append(f"            if (c > {i % 9}.0) {{ b = c; break; }}\n")
        s.append("            else { d = d * 0.99 + a; continue; }\n        }\n    }\n")
        s.append(f"    else\n    {{\n        switch ((idx + {i}) % 4)\n        {{\n")
        s.append("        case 0: a -= d; break;\n        case 1: b += c; break;\n")
        s.append("        case 2: c *= 1.01; break;\n        default: d -= a * 0.1;\n        }\n    }\n")
    s.append("    outBuf[idx] = a + b + c + d;\n}\n")
    return {"control_flow_ssa.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Core compiler-stage buckets
# --------------------------------------------------------------------------- #

def gen_parse(n):
    """Large but semantically trivial source: many functions, each a long
    arithmetic expression. Stresses lex/parse with cheap sema."""
    s = [_HEADER, _buf()]
    for i in range(n):
        terms = " ".join(
            f"+ {j % 9}.0 * x" if j % 2 else f"- {j % 7}.0 * x" for j in range(40)
        )
        s.append(f"float p_{i}(float x) {{ return x {terms}; }}\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain() { outBuf[0] = p_0(outBuf[0]); }\n")
    return {"parse.slang": "".join(s)}


def gen_sema_generics(n):
    """n distinct generic functions with interface constraints, each instantiated
    at several concrete types. Stresses semantic checking, generic constraint
    satisfaction and instantiation in the front-end."""
    s = [_HEADER, _buf()]
    for i in range(n):
        s.append(
            f"T poly_{i}<T : IArithmetic>(T a, T b) {{ return a * a + b * a + a + b; }}\n"
        )
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n")
    s.append("    float facc = 0.0; int iacc = 0; uint uacc = 0u;\n")
    s.append("    float fx = outBuf[0]; int ix = int(outBuf[0]); uint ux = uint(outBuf[0]);\n")
    for i in range(n):
        s.append(f"    facc += poly_{i}<float>(fx, fx + 1.0);\n")
        s.append(f"    iacc += poly_{i}<int>(ix, ix + 1);\n")
        s.append(f"    uacc += poly_{i}<uint>(ux, ux + 1u);\n")
    s.append("    outBuf[0] = facc + float(iacc) + float(uacc);\n}\n")
    return {"sema_generics.slang": "".join(s)}


# --------------------------------------------------------------------------- #
# Type checking: operator overload resolution + implicit conversions
# --------------------------------------------------------------------------- #
# These isolate the front-end type-checker's most quietly expensive work: every
# binary operator and every cross-type assignment runs overload resolution over
# a candidate set and ranks implicit-conversion costs. `parse` deliberately uses
# uniform-`float` arithmetic so each operator matches one overload trivially;
# the workloads below force a *mixed-type* decision at every node instead.

def gen_operator_typecheck(n):
    """`n` functions, each a long arithmetic expression whose operands alternate
    among float/int/uint (typed locals and literals of differing kinds). Every
    `+`/`-`/`*` must resolve the builtin arithmetic operator overload set and
    insert an implicit conversion to the common type — the "checking the types of
    1 and 2 in 1 + 2" cost, multiplied across many nodes. Contrast `parse`, whose
    same-type float expressions skip overload ranking. Module mode -> the signal
    is SemanticChecking, not codegen."""
    s = [_HEADER, _buf()]
    # Each term mixes operand types so the common-type/coercion decision is
    # non-trivial; all conversions are standard widening (int/uint -> float) so
    # the source compiles cleanly across the whole release window.
    terms = [
        "+ 2 * fx", "- ix + 3u", "+ 4.0 * ix", "- ux * 5", "+ fx * 6u",
        "- 7 + ux", "+ ix * 8.0", "- 9u + fx", "+ ux * 10", "- fx * 11",
    ]
    for i in range(n):
        body = " ".join(terms[(i + j) % len(terms)] for j in range(24))
        s.append(
            f"float op_{i}(float fx, int ix, uint ux) {{ return fx {body}; }}\n"
        )
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    s.append("    float fx = outBuf[0]; int ix = int(outBuf[0]); uint ux = uint(outBuf[0]);\n")
    # Cap computeMain call sites at 64: beyond this the entry point itself (not
    # the per-function checking cost we're measuring) becomes the bottleneck.
    for i in range(min(n, 64)):
        s.append(f"    acc += op_{i}(fx, ix, ux);\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"operator_typecheck.slang": "".join(s)}


def gen_implicit_conversion(n):
    """`n` functions, each a cascade of cross-type conversions: scalar widening
    (int/uint -> float), splats, mixed initializer lists (per-element coercion),
    vector compose/truncate, and explicit narrowing. Stresses the coercion /
    conversion-cost engine in semantic checking rather than operator overloading."""
    s = [_HEADER, _buf()]
    for i in range(n):
        b = [f"float conv_{i}()", "{"]
        b.append(f"    int i = {i % 7}; uint u = {i % 5}u; float f = {i % 9}.0;")
        b.append("    float a = i;")                      # int -> float (widen)
        b.append("    float b = u;")                      # uint -> float (widen)
        b.append("    float2 v2 = f;")                    # scalar -> vector splat
        b.append("    float3 v3 = float3(i, u, f);")      # mixed init: per-elem coerce
        b.append("    float4 v4 = float4(v3, a);")        # vector compose
        b.append("    int2 iv = int2(v2);")               # float2 -> int2 (explicit)
        b.append("    float3 w = v4.xyz;")                # swizzle / truncate
        b.append("    return a + b + v2.x + v3.y + v4.w + float(iv.x) + w.z;")
        b.append("}")
        s.append("\n".join(b) + "\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    # Cap computeMain call sites at 64: beyond this the entry point itself (not
    # the per-function checking cost we're measuring) becomes the bottleneck.
    for i in range(min(n, 64)):
        s.append(f"    acc += conv_{i}();\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"implicit_conversion.slang": "".join(s)}


def gen_overload_resolution(n):
    """A large user-defined overload set (`pick`/`pick2`, scalar + vector + two-arg
    candidates), then `n` call sites with rotating argument types. Every call
    enumerates all candidates and ranks them by conversion cost to choose the best
    match — isolating the candidate-ranking cost that scales with overload-set
    size times call-site count."""
    s = [_HEADER, _buf()]
    for ty in ("float", "int", "uint", "float2", "float3", "float4"):
        s.append(f"float pick({ty} x) {{ return float(x[0] + x[0]); }}\n"
                 if ty.startswith("float") and ty != "float"
                 else f"float pick({ty} x) {{ return float(x) + 1.0; }}\n")
    # two-argument overloads exercise multi-parameter rank comparison
    for a, bb in (("float", "float"), ("int", "float"), ("float", "int"),
                  ("int", "int"), ("uint", "float"), ("float", "uint")):
        s.append(f"float pick2({a} a, {bb} b) {{ return float(a) + float(b); }}\n")
    s.append("\n")
    args1 = ["1.0", "2", "3u", "float2(1.0)", "float3(1.0)", "float4(1.0)"]
    args2 = [("1.0", "2.0"), ("3", "4.0"), ("5.0", "6"), ("7", "8"),
             ("9u", "10.0"), ("11.0", "12u")]
    for i in range(n):
        a = args1[i % len(args1)]
        p, q = args2[i % len(args2)]
        s.append(f"float call_{i}() {{ return pick({a}) + pick2({p}, {q}); }}\n")
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    # Cap computeMain call sites at 64: beyond this the entry point itself (not
    # the per-function checking cost we're measuring) becomes the bottleneck.
    for i in range(min(n, 64)):
        s.append(f"    acc += call_{i}();\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"overload_resolution.slang": "".join(s)}


def gen_specialization(n):
    """A generic struct over a type parameter, instantiated at n distinct
    wrapper types. Forces specializeModule to clone the generic n ways."""
    s = [_HEADER, _buf()]
    s.append("interface IVal { float get(); }\n\n")
    for i in range(n):
        s.append(f"struct V{i} : IVal {{ float get() {{ return {i}.0 + 1.0; }} }}\n")
    s.append("\nstruct Box<T : IVal> { T v; float compute() { return v.get() * 2.0 + v.get(); } }\n\n")
    s.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float acc = 0.0;\n")
    for i in range(n):
        s.append(f"    {{ Box<V{i}> b; acc += b.compute(); }}\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"specialization.slang": "".join(s)}


def gen_inlining(n):
    """n [ForceInline] functions in bounded-depth groups. The inliner collapses
    each group into its group-top; the entry sums all group-tops, giving the SSA
    simplifier large bodies to chew on. Scales by breadth (bounded nesting)."""
    s = [_HEADER, _buf()]
    group_tops = []
    for i in range(n):
        if i % _GROUP_DEPTH == 0:
            s.append(f"[ForceInline] float step_{i}(float x) {{ return x * 1.01 + sin(x); }}\n")
        else:
            s.append(
                f"[ForceInline] float step_{i}(float x) {{ float t = step_{i - 1}(x); return t * 1.01 + cos(t) - sin(x * 0.5); }}\n"
            )
        if (i % _GROUP_DEPTH == _GROUP_DEPTH - 1) or i == n - 1:
            group_tops.append(i)
    s.append('\n[shader("compute")]\n[numthreads(1,1,1)]\n')
    s.append("void computeMain()\n{\n    float x = outBuf[0]; float acc = 0.0;\n")
    for top in group_tops:
        s.append(f"    acc += step_{top}(x);\n")
    s.append("    outBuf[0] = acc;\n}\n")
    return {"inlining.slang": "".join(s)}


def gen_codegen(n):
    """A single moderately complex shader. Compiled to multiple targets by the
    harness (same source, varying -target) to isolate generateOutput cost.
    ``n`` scales the amount of straight-line math the backend must emit."""
    s = [_HEADER, _buf()]
    s.append('[shader("compute")]\n[numthreads(64,1,1)]\n')
    s.append("void computeMain(uint3 tid : SV_DispatchThreadID)\n{\n")
    s.append("    float x = outBuf[tid.x];\n    float acc = x;\n")
    for i in range(n):
        s.append(
            f"    acc = acc * 1.0009 + sin(acc + {i}.0) * 0.5 - cos(acc * 0.5) * 0.25 + sqrt(abs(acc) + {i + 1}.0);\n"
        )
    s.append("    outBuf[tid.x] = acc;\n}\n")
    return {"codegen.slang": "".join(s)}


def gen_module_link(n):
    """n importable modules plus a main that imports and uses all of them. The
    harness precompiles each module to .slang-module, then compiles main against
    them, stressing module read + linkIR."""
    files = {}
    for i in range(n):
        files[f"mod_{i}.slang"] = (
            _HEADER
            + f"module mod_{i};\n\n"
            + f"public float mfun_{i}(float x) {{ return x * {i + 1}.0009 + sin(x + {i}.0); }}\n"
        )
    main = [_HEADER]
    for i in range(n):
        main.append(f"import mod_{i};\n")
    main.append("\n" + _buf())
    main.append('[shader("compute")]\n[numthreads(1,1,1)]\n')
    main.append("void computeMain()\n{\n    float acc = outBuf[0];\n")
    for i in range(n):
        main.append(f"    acc = mfun_{i}(acc);\n")
    main.append("    outBuf[0] = acc;\n}\n")
    files["link_main.slang"] = "".join(main)
    return files


# --------------------------------------------------------------------------- #
# Real-shader corpus (not generated). Copy corpus files into corpus/<name>/
# before running the suite (CI does this via actions/checkout of MDL-SDK).
# --------------------------------------------------------------------------- #

def _read_corpus(name):
    d = os.path.join(_CORPUS, name)
    if not os.path.isdir(d):
        raise FileNotFoundError(
            f"corpus '{name}' missing at {d}; copy .slang files there before running"
        )
    out = {}
    for fn in sorted(os.listdir(d)):
        if fn.endswith(".slang"):
            with open(os.path.join(d, fn), "rb") as fh:
                out[fn] = fh.read().decode("utf-8", "replace")
    if not out:
        raise FileNotFoundError(f"no .slang files in corpus '{name}' ({d})")
    return out


def gen_mdl_dxr(n):
    """Real MDL/DXR path-tracing shaders (shader-slang/MDL-SDK). `n` is ignored
    (fixed corpus). Compiled monolithically from hit.slang, which imports the
    rest. This is a holistic real-world compile-time number."""
    return _read_corpus("mdl")
