@echo off
rem This batch file helps coding agents (e.g. Codex, Claude Code, Copilot) build
rem the Slang project on Windows sandbox environments.
rem
rem The script loads the MSVC environment via vcvarsall.bat, configures the project
rem using the Visual Studio 2022 generator (`vs2022-dev` preset), and builds it from
rem the command line. It prefers locally cached dependencies so the configure step
rem does not need to fetch packages over the network.
rem
rem Usage:
rem   extras\win-sandbox-build.bat [debug|release|releaseWithDebugInfo|minSizeRel] [x64|arm64|Win32] [target...]
rem
rem By default this script builds `slangc`, `slang-test`, and `slangi`. This
rem avoids the Visual Studio CLI `ALL_BUILD` aggregation path, which is not
rem reliable in sandboxed runs.
rem The build is also kept single-node because `/m` has proven flaky in sandboxed
rem MSBuild invocations.

setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%..") do set "REPO_ROOT=%%~fI"
set "CONFIGURE_PRESET=vs2022-dev"
set "DEFAULT_BUILD_KIND=debug"
set "DEFAULT_ARCH=x64"
set "DEFAULT_BUILD_TARGETS=slangc slang-test slangi"

set "BUILD_KIND=%DEFAULT_BUILD_KIND%"
set "TARGET_ARCH=%DEFAULT_ARCH%"
set "BUILD_TARGETS="

if "%~1"=="" goto build_kind_done
if /i "%~1"=="debug" set "BUILD_KIND=debug" & shift & goto build_kind_done
if /i "%~1"=="release" set "BUILD_KIND=release" & shift & goto build_kind_done
if /i "%~1"=="releaseWithDebugInfo" set "BUILD_KIND=releaseWithDebugInfo" & shift & goto build_kind_done
if /i "%~1"=="minSizeRel" set "BUILD_KIND=minSizeRel" & shift & goto build_kind_done
:build_kind_done

if "%~1"=="" goto target_arch_done
if /i "%~1"=="x64" set "TARGET_ARCH=x64" & shift & goto target_arch_done
if /i "%~1"=="arm64" set "TARGET_ARCH=arm64" & shift & goto target_arch_done
if /i "%~1"=="Win32" set "TARGET_ARCH=Win32" & shift & goto target_arch_done
:target_arch_done

if "%~1"=="" goto build_targets_done
set "BUILD_TARGETS=%~1"
shift
:collect_build_targets
if "%~1"=="" goto build_targets_done
set "BUILD_TARGETS=!BUILD_TARGETS! %~1"
shift
goto collect_build_targets
:build_targets_done

if not defined BUILD_TARGETS set "BUILD_TARGETS=%DEFAULT_BUILD_TARGETS%"

set "BUILD_PRESET=%BUILD_KIND%"
if /i "%BUILD_KIND%"=="debug" set "BUILD_PRESET=vs2022-dev-debug"
if /i "%BUILD_KIND%"=="release" set "BUILD_PRESET=vs2022-dev-release"
if /i "%BUILD_KIND%"=="releaseWithDebugInfo" set "BUILD_PRESET=vs2022-dev-releaseWithDebugInfo"
if /i "%BUILD_KIND%"=="minSizeRel" set "BUILD_PRESET=vs2022-dev-minSizeRel"

set "VCVARSALL="

if defined VSINSTALLDIR if exist "%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat" (
    set "VCVARSALL=%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat"
)

if not defined VCVARSALL (
    set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
    if exist "%VSWHERE%" (
        for /f "usebackq delims=" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
            if exist "%%~I\VC\Auxiliary\Build\vcvarsall.bat" (
                set "VCVARSALL=%%~I\VC\Auxiliary\Build\vcvarsall.bat"
            )
        )
    )
)

if not defined VCVARSALL (
    for %%I in (
        "%ProgramFiles%\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvarsall.bat"
        "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat"
        "%ProgramFiles%\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
        "%ProgramFiles%\Microsoft Visual Studio\18\Insiders\VC\Auxiliary\Build\vcvarsall.bat"
    ) do (
        if not defined VCVARSALL if exist "%%~I" set "VCVARSALL=%%~I"
    )
)

if not defined VCVARSALL (
    echo Failed to locate vcvarsall.bat.
    echo Install Visual Studio C++ tools or update this script with the correct path.
    exit /b 1
)

where cmake.exe >nul 2>&1
if errorlevel 1 (
    echo Failed to find cmake.exe in PATH.
    exit /b 1
)

echo Loading MSVC environment from:
echo   %VCVARSALL%
call "%VCVARSALL%" %TARGET_ARCH%
if errorlevel 1 (
    echo vcvarsall.bat failed.
    exit /b 1
)

pushd "%REPO_ROOT%"

set "LOCAL_CACHE_INIT_FILE=%REPO_ROOT%\build\win-sandbox-build-local-deps.cmake"
set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT=0

if not exist "%REPO_ROOT%\build" (
    mkdir "%REPO_ROOT%\build"
)

> "%LOCAL_CACHE_INIT_FILE%" echo # Auto-generated by extras\win-sandbox-build.bat
>> "%LOCAL_CACHE_INIT_FILE%" echo set^(SLANG_IGNORE_ABORT_MSG ON CACHE BOOL "" FORCE^)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\dxc-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for DXC: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_DXC "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\winpix-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for WINPIX: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_WINPIX "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\agility_sdk-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for AGILITY_SDK: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_AGILITY_SDK "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\aftermath_sdk-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for AFTERMATH_SDK: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_AFTERMATH_SDK "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\nvapi-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for NVAPI: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_NVAPI "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\optix_8_0-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for OPTIX_8_0: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_OPTIX_8_0 "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\optix_8_1-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for OPTIX_8_1: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_OPTIX_8_1 "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\optix_9_0-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for OPTIX_9_0: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_OPTIX_9_0 "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\vulkan_headers-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for VULKAN_HEADERS: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_VULKAN_HEADERS "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\metal_cpp-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for METAL_CPP: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_METAL_CPP "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\dawn-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for DAWN: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_DAWN "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\_deps\glfw-src"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    set /a LOCAL_FETCHCONTENT_OVERRIDE_COUNT+=1
    echo   Using local FetchContent source for GLFW: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_SOURCE_DIR_GLFW "!LOCAL_PATH!" CACHE PATH "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\webgpu_dawn-windows-x64"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    echo   Using local package cache for SLANG_WEBGPU_DAWN_BINARY_URL: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(SLANG_WEBGPU_DAWN_BINARY_URL "!LOCAL_PATH!" CACHE STRING "" FORCE^)
)

set "LOCAL_PATH=%REPO_ROOT%\build\slang-tint-windows-x64"
if exist "%LOCAL_PATH%" (
    set "LOCAL_PATH=!LOCAL_PATH:\=/!"
    echo   Using local package cache for SLANG_SLANG_TINT_BINARY_URL: !LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(SLANG_SLANG_TINT_BINARY_URL "!LOCAL_PATH!" CACHE STRING "" FORCE^)
)

set "LLVM_LOCAL_PATH="
for /d %%I in ("%REPO_ROOT%\build\slang-*-windows-x86_64") do (
    if not defined LLVM_LOCAL_PATH if exist "%%~fI" set "LLVM_LOCAL_PATH=%%~fI"
)
for %%I in ("%REPO_ROOT%\build\slang-*-windows-x86_64.zip") do (
    if not defined LLVM_LOCAL_PATH if exist "%%~fI" set "LLVM_LOCAL_PATH=%%~fI"
)
if defined LLVM_LOCAL_PATH (
    set "LLVM_LOCAL_PATH=!LLVM_LOCAL_PATH:\=/!"
    echo   Using local package cache for SLANG_SLANG_LLVM_BINARY_URL: !LLVM_LOCAL_PATH!
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(SLANG_SLANG_LLVM_BINARY_URL "!LLVM_LOCAL_PATH!" CACHE STRING "" FORCE^)
)

if not "!LOCAL_FETCHCONTENT_OVERRIDE_COUNT!"=="0" (
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_FULLY_DISCONNECTED ON CACHE BOOL "" FORCE^)
    >> "%LOCAL_CACHE_INIT_FILE%" echo set^(FETCHCONTENT_UPDATES_DISCONNECTED ON CACHE BOOL "" FORCE^)
    echo Reusing !LOCAL_FETCHCONTENT_OVERRIDE_COUNT! locally cached FetchContent package^(s^) in offline mode.
)

echo Configuring with preset "%CONFIGURE_PRESET%"...
cmake.exe --preset "%CONFIGURE_PRESET%" -C "%LOCAL_CACHE_INIT_FILE%"
set "CONFIGURE_EXIT=%ERRORLEVEL%"
if exist "%LOCAL_CACHE_INIT_FILE%" del /q "%LOCAL_CACHE_INIT_FILE%" >nul 2>&1
if not "%CONFIGURE_EXIT%"=="0" (
    popd
    exit /b %CONFIGURE_EXIT%
)

echo Building with preset "%BUILD_PRESET%" for target^(s^) "%BUILD_TARGETS%"...
cmake.exe --build --preset "%BUILD_PRESET%" --verbose --target %BUILD_TARGETS%
set "BUILD_EXIT=%ERRORLEVEL%"

popd
exit /b %BUILD_EXIT%
