name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['debug', 'release']
        compiler: ['gcc', 'clang']
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: build
      run: 
        CC=${{matrix.compiler}}
        CONFIGURATION=${{matrix.configuration}}
        OS=linux-64
        source ./github_build.sh
    - name: test
      run: 
        CONFIGURATION=${{matrix.configuration}}
        CC=${{matrix.compiler}}
        OS=linux-64
        source ./github_test.sh