name: Check the IR stable name table

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-cmdline-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev
          make -C external/lua
          external/lua/lua -v

      - name: Check Stable Names Table
        id: check
        run: |
          ./external/lua/lua extras/check-ir-stable-names.lua check
        continue-on-error: true

      - name: Update and Show Diff if Check Failed
        if: steps.check.outcome == 'failure'
        run: |
          echo "Check failed. Running update..."
          ./external/lua/lua extras/check-ir-stable-names.lua update

          echo -e "\n=== Diff of changes made ==="
          git diff --no-index --color=always source/slang/slang-ir-insts-stable-names.lua || true

          # Also create a summary for GitHub Actions
          echo "## IR Stable Names Table Update Required" >> $GITHUB_STEP_SUMMARY
          echo "The following changes need to be made to \`source/slang/slang-ir-insts-stable-names.lua\`:" >> $GITHUB_STEP_SUMMARY
          echo '```diff&#x27; &gt;&gt; $GITHUB_STEP_SUMMARY
          git diff --no-index source/slang/slang-ir-insts-stable-names.lua &gt;&gt; $GITHUB_STEP_SUMMARY || true
          echo &#x27;```' >> $GITHUB_STEP_SUMMARY

          # Fail the job since the check failed
          exit 1
