name: Internal-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    strategy:
      matrix:
        include:
          # Self-hosted falcor tests
          - os: windows
            runs-on: [Windows, self-hosted]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "false"
          fetch-depth: "0"
      - name: Setup jd tools to git-bash
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_PATH -Value "C:\\Program Files\\Git\\bin"
          Add-Content -Path $env:GITHUB_PATH -Value "C:\\Program Files\\Git\\usr\\bin"
          Invoke-WebRequest https://github.com/jqlang/jq/releases/latest/download/jq-win64.exe -OutFile ".\\jq.exe"
          echo $PWD

      - name: Run Internal CI Pipeline
        shell: bash
        env:
          MY_TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}
        run: .github/workflows/internal_test.sh $PR_NUMBER $MY_TEST_SECRET
