name: Linux/ARM64 Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:

    runs-on: ['self-hosted', 'Linux', 'ARM64']
    strategy:
      matrix:
        configuration: ['release']
        compiler: ['gcc']
        platform: ['aarch64']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: build
      run: |
        CC=${{matrix.compiler}}
        CONFIGURATION=${{matrix.configuration}}
        ARCH=${{matrix.platform}}
        TARGETARCH=${{matrix.platform}}
        if [[ "$CC" == "clang" ]]; then
          CFLAGS=-Werror
          CPPFLAGS=-Werror
          CXXFLAGS=-Werror
        fi
        source ./github_build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: slang-build-${{matrix.configuration}}-${{matrix.platform}}-${{matrix.compiler}}
        path: |
          slang.h
          slang-com-helper.h
          slang-com-ptr.h
          slang-tag-version.h
          slang-gfx.h
          prelude/*.h
          bin/**/*.dll
          bin/**/*.exe
          bin/**/*.so
          bin/**/slangc
          bin/**/slangd
          docs/*.md
    - name: test
      run: 
        CONFIGURATION=${{matrix.configuration}}
        CC=${{matrix.compiler}}
        ARCH=${{matrix.platform}}
        PATH="${PATH:+${PATH}:}$(pwd)/external/slang-binaries/spirv-tools/$(uname -m)-linux/bin"
        source .github/github_test.sh
